{% macro get_organization_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "cover_photo_v_2_crop_info_height", "datatype": dbt.type_int()},
    {"name": "cover_photo_v_2_crop_info_width", "datatype": dbt.type_int()},
    {"name": "cover_photo_v_2_crop_info_x", "datatype": dbt.type_int()},
    {"name": "cover_photo_v_2_crop_info_y", "datatype": dbt.type_int()},
    {"name": "cover_photo_v_2_cropped", "datatype": dbt.type_string()},
    {"name": "cover_photo_v_2_original", "datatype": dbt.type_string()},
    {"name": "default_locale_country", "datatype": dbt.type_string()},
    {"name": "default_locale_language", "datatype": dbt.type_string()},
    {"name": "description_localized", "datatype": dbt.type_string()},
    {"name": "description_preferred_locale_country", "datatype": dbt.type_string()},
    {"name": "description_preferred_locale_language", "datatype": dbt.type_string()},
    {"name": "founded_on_day", "datatype": dbt.type_int()},
    {"name": "founded_on_month", "datatype": dbt.type_int()},
    {"name": "founded_on_year", "datatype": dbt.type_int()},
    {"name": "id", "datatype": dbt.type_int()},
    {"name": "localized_description", "datatype": dbt.type_string()},
    {"name": "localized_name", "datatype": dbt.type_string()},
    {"name": "localized_website", "datatype": dbt.type_string()},
    {"name": "logo_v_2_crop_info_height", "datatype": dbt.type_int()},
    {"name": "logo_v_2_crop_info_width", "datatype": dbt.type_int()},
    {"name": "logo_v_2_crop_info_x", "datatype": dbt.type_int()},
    {"name": "logo_v_2_crop_info_y", "datatype": dbt.type_int()},
    {"name": "logo_v_2_cropped", "datatype": dbt.type_string()},
    {"name": "logo_v_2_original", "datatype": dbt.type_string()},
    {"name": "name_localized", "datatype": dbt.type_string()},
    {"name": "name_preferred_locale_country", "datatype": dbt.type_string()},
    {"name": "name_preferred_locale_language", "datatype": dbt.type_string()},
    {"name": "organization_status", "datatype": dbt.type_string()},
    {"name": "organization_type", "datatype": dbt.type_string()},
    {"name": "overview_photo_v_2_crop_info_height", "datatype": dbt.type_int()},
    {"name": "overview_photo_v_2_crop_info_width", "datatype": dbt.type_int()},
    {"name": "overview_photo_v_2_crop_info_x", "datatype": dbt.type_int()},
    {"name": "overview_photo_v_2_crop_info_y", "datatype": dbt.type_int()},
    {"name": "overview_photo_v_2_cropped", "datatype": dbt.type_string()},
    {"name": "overview_photo_v_2_original", "datatype": dbt.type_string()},
    {"name": "parent_relationship_parent_id", "datatype": dbt.type_int()},
    {"name": "parent_relationship_status", "datatype": dbt.type_string()},
    {"name": "parent_relationship_type", "datatype": dbt.type_string()},
    {"name": "primary_organization_type", "datatype": dbt.type_string()},
    {"name": "school_attributes_hierarchy_classification", "datatype": dbt.type_string()},
    {"name": "school_attributes_legacy_school", "datatype": dbt.type_string()},
    {"name": "school_attributes_type", "datatype": dbt.type_string()},
    {"name": "school_attributes_year_level", "datatype": dbt.type_string()},
    {"name": "staff_count_range", "datatype": dbt.type_string()},
    {"name": "vanity_name", "datatype": dbt.type_string()},
    {"name": "version_tag", "datatype": dbt.type_string()},
    {"name": "website_localized", "datatype": dbt.type_string()},
    {"name": "website_preferred_locale_country", "datatype": dbt.type_string()},
    {"name": "website_preferred_locale_language", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}
