name: 'qualtrics_source_integration_tests'
version: '0.2.2'
profile: 'integration_tests'
config-version: 2

vars:
  qualtrics_schema: qualtrics_source_integration_tests_03
  qualtrics__using_core_contacts: true
  qualtrics__using_core_mailing_lists: true

models:
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ['spark','databricks'] else true }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

seeds:
  qualtrics_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
      directory_unsubscribe_date: timestamp
      response_completed_at: timestamp
      last_accessed: timestamp
      account_creation_date: timestamp
      response_started_at: timestamp
      account_expiration_date: timestamp
      last_login_date: timestamp
      password_expiration_date: timestamp
      password_last_changed_date: timestamp
      unsubscribe_date: timestamp
    directory_contact:
      +column_types:
        phone: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar' }}"
