{% macro column_list_to_dict(column_list) %}
{# This macro converts the list of dictionaries generated by the `get_*_columns` macros into a dictionary of dictionaries for use in the `coalesce_rename` macro. This conversion is necessary so that each column dictionary entry can be accessed by a key, rather than iterating through a list. #}
    {%- set column_dict = {} -%}
    {%- for col in column_list -%}
        {%- do column_dict.update({col.name: col}) if not col.is_rename -%}
    {%- endfor -%}
    {{ return(column_dict) }}

{% endmacro %}