version: 2

models:
  - name: cpa_and_roas
    description: >
      Aggregated ad spend and attribution data, with calculated metrics for cost per acquisition (CPA) and return on advertising spend (ROAS).

    columns:
      - name: date_month
        description: The month of the data.
        tests:
          - not_null

      - name: utm_source
        description: The source of the traffic (e.g., Google, Facebook).
        tests:
          - not_null

      - name: attribution_points
        description: The total attribution points.
        tests:
          - not_null

      - name: attribution_revenue
        description: The total attributed revenue.
        tests:
          - not_null

      - name: total_spend
        description: The total amount of money spent on ads.
        tests:
          - not_null

      - name: cost_per_acquisition
        description: The cost per acquisition for the month, calculated as total spend divided by attribution points.
        tests:
          - not_null

      - name: return_on_advertising_spend
        description: The return on advertising spend for the month, calculated as attributed revenue divided by total spend.
        tests:
          - not_null
