config-version: 2
name: 'asana'
version: 0.8.1
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  +materialized: table

profile: 'asana'

vars:
  asana_schema: main
  asana_source:
    asana_user_identifier: "user_data"
    asana_project_identifier: "project_data"
    asana_task_identifier: "task_data"
    asana_story_identifier: "story_data"
    asana_team_identifier: "team_data"
    asana_tag_identifier: "tag_data"
    asana_project_task_identifier: "project_task_data"
    asana_task_follower_identifier: "task_follower_data"
    asana_task_tag_identifier: "task_tag_data"
    asana_section_identifier: "section_data"
    asana_task_section_identifier: "task_section_data"

  asana:
    project_task: "{{ ref('stg_asana__project_task') }}"
    project: "{{ ref('stg_asana__project') }}"
    section: "{{ ref('stg_asana__section') }}"
    story: "{{ ref('stg_asana__story') }}"
    tag: "{{ ref('stg_asana__tag') }}"
    task_follower: "{{ ref('stg_asana__task_follower') }}"
    task_section: "{{ ref('stg_asana__task_section') }}"
    task_tag: "{{ ref('stg_asana__task_tag') }}"
    task: "{{ ref('stg_asana__task') }}"
    team: "{{ ref('stg_asana__team') }}"
    user: "{{ ref('stg_asana__user') }}"



seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  main:
    +all_varchar: true  # 强制所有列为字符串
    +column_types:
      _fivetran_synced: timestamp
    user_data:
      +column_types:
        id: "string"
    project_data:
      +column_types:
        id: "string"
        owner_id: "string"
        team_id: "string"
        workspace_id: "string"
    task_data:
      +column_types:
        id: "string"
        assignee_id: "string"
        completed_by_id: "string"
        parent_id: "string"
        workspace_id: "string"
        completed_at: timestamp
        created_at: timestamp
        due_on: timestamp
        due_at: timestamp
        modified_at: timestamp
        start_on: timestamp
        _fivetran_synced: timestamp
    story_data:
      +column_types:
        id: "string"
        created_by_id: "string"
        target_id: "string"
    team_data:
      +column_types:
        id: "string"
        organization_id: "string"
    tag_data:
      +column_types:
        id: "string"
        workspace_id: "string"
    project_task_data:
      +column_types:
        project_id: "string"
        task_id: "string"
    task_follower_data:
      +column_types:
        user_id: "string"
        task_id: "string"
    task_tag_data:
      +column_types:
        tag_id: "string"
        task_id: "string"
    section_data:
      +column_types:
        id: "string"
        project_id: "string"
    task_section_data:
      +column_types:
        section_id: "string"
        task_id: "string"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']