{{
    fivetran_utils.union_data(
        table_identifier='organization_role', 
        database_variable='workday_database', 
        schema_variable='workday_schema', 
        default_database=target.database,
        default_schema='workday',
        default_variable='organization_role',
        union_schema_variable='workday_union_schemas',
        union_database_variable='workday_union_databases'
    )
}}
