version: 2

models: 
  - name: fct_billed_patient_claims
    description: record per claim with payment, patient and diagnosis data
    columns:
      - name: claim_id
        tests:
          - unique
          - not_null
      - name: total_charge_amount
        description: total amount charged by the practice on the claim
        tests:
          - not_negative
      - name: total_paid_amount
        description: total amount paid by the insurance provider or patient on the claim
        tests:
          - not_negative

  - name: dim_doctors
    description: "A dimension table representing doctors and their associated specialties."
    columns:
      - name: doctor_id
        description: "Unique identifier for the doctor."
        tests:
          - unique
          - not_null
      - name: npi
        description: "National Provider Identifier (NPI) for the doctor."
        tests:
          - unique
          - not_null
      - name: practice_id
        description: "The practice ID associated with the doctor."
        tests:
          - not_null
      - name: first_name
        description: "Doctor's first name."
      - name: last_name
        description: "Doctor's last name."
      - name: doctor_name
        description: "Full name of the doctor."
      - name: billing_address
        description: "The billing address of the doctor."
      - name: zip_code
        description: "The zip code of the billing address."
      - name: state
        description: "The state of the doctor's practice."
      - name: country
        description: "The country of the doctor's practice."
      - name: created_at
        description: "Timestamp of when the doctor record was created."
      - name: last_logged_in_at
        description: "Timestamp of when the doctor last logged in."
      - name: specialty_category
        description: "The category of the doctor's specialty."
      - name: specialty_name
        description: "The specific specialty of the doctor."
    refs:
      - name: stg_doctors
        description: "References the source table containing raw doctor data."
      - name: stg_doc_specialties
        description: "References the source table containing raw doctor specialties data."

  - name: dim_patients
    description: "A dimension table representing patients and their associated details."
    columns:
      - name: patient_id
        description: "Unique identifier for the patient."
        tests:
          - unique
          - not_null
      - name: practice_id
        description: "The practice ID associated with the patient."
        tests:
          - not_null
      - name: first_name
        description: "Patient's first name."
      - name: last_name
        description: "Patient's last name."
      - name: patient_name
        description: "Full name of the patient."
      - name: billing_address
        description: "The billing address of the patient."
      - name: zip_code
        description: "The zip code of the billing address."
      - name: state
        description: "The state of the patient's residence."
      - name: country
        description: "The country of the patient's residence."
      - name: email
        description: "Patient's email address."
      - name: is_diabetic
        description: "Indicates whether the patient is diabetic."
      - name: is_test
        description: "Indicates whether the patient is a test entry."
      - name: date_of_birth
        description: "The patient's date of birth."
      - name: created_at
        description: "Timestamp of when the patient record was created."
      - name: last_logged_in_at
        description: "Timestamp of when the patient last logged in."
    refs:
      - name: stg_patients
        description: "References the source table containing raw patient data."