name: 'qualtrics'
version: '0.2.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"] 

profile: 'qualtrics'



vars:
  qualtrics_schema: main
  qualtrics_source:
    qualtrics_user_identifier: "user"
    qualtrics_survey_identifier: "survey"
    qualtrics_question_identifier: "question"
    qualtrics_question_response_identifier: "question_response"
    qualtrics_question_option_identifier: "question_option"
    qualtrics_survey_response_identifier: "survey_response"
    qualtrics_sub_question_identifier: "sub_question"
    qualtrics_survey_version_identifier: "survey_version"
    qualtrics_survey_embedded_data_identifier: "survey_embedded_data"
    qualtrics_block_identifier: "block"
    qualtrics_block_question_identifier: "block_question"
    qualtrics_directory_identifier: "directory"
    qualtrics_directory_contact_identifier: "directory_contact"
    qualtrics_directory_mailing_list_identifier: "directory_mailing_list"
    qualtrics_contact_mailing_list_membership_identifier: "contact_mailing_list_membership"
    qualtrics_distribution_identifier: "distribution"
    qualtrics_distribution_contact_identifier: "distribution_contact"
    qualtrics_core_contact_identifier: "core_contact"
    qualtrics_core_mailing_list_identifier: "core_mailing_list"
  qualtrics:
    user: "{{ ref('stg_qualtrics__user') }}"
    survey: "{{ ref('stg_qualtrics__survey') }}"
    question: "{{ ref('stg_qualtrics__question') }}"
    question_response: "{{ ref('stg_qualtrics__question_response') }}"
    question_option: "{{ ref('stg_qualtrics__question_option') }}"
    survey_response: "{{ ref('stg_qualtrics__survey_response') }}"
    sub_question: "{{ ref('stg_qualtrics__sub_question') }}"
    survey_version: "{{ ref('stg_qualtrics__survey_version') }}"
    survey_embedded_data: "{{ ref('stg_qualtrics__survey_embedded_data') }}"
    block: "{{ ref('stg_qualtrics__block') }}"
    block_question: "{{ ref('stg_qualtrics__block_question') }}"
    directory: "{{ ref('stg_qualtrics__directory') }}"
    directory_contact: "{{ ref('stg_qualtrics__directory_contact') }}"
    directory_mailing_list: "{{ ref('stg_qualtrics__directory_mailing_list') }}"
    contact_mailing_list_membership: "{{ ref('stg_qualtrics__contact_mailing_list_membership') }}"
    distribution: "{{ ref('stg_qualtrics__distribution') }}"
    distribution_contact: "{{ ref('stg_qualtrics__distribution_contact') }}"
    core_contact: "{{ ref('stg_qualtrics__core_contact') }}"
    core_mailing_list: "{{ ref('stg_qualtrics__core_mailing_list') }}"



models:
  qualtrics:
    +materialized: table
    intermediate:
      +materialized: ephemeral
