name: 'google_play'
version: '0.4.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  google_play:
    stats_installs_app_version: "{{ ref('stg_google_play__stats_installs_app_version') }}"
    stats_crashes_app_version: "{{ ref('stg_google_play__stats_crashes_app_version') }}"
    stats_ratings_app_version: "{{ ref('stg_google_play__stats_ratings_app_version') }}"
    stats_installs_device: "{{ ref('stg_google_play__stats_installs_device') }}"
    stats_ratings_device: "{{ ref('stg_google_play__stats_ratings_device') }}"
    stats_installs_os_version: "{{ ref('stg_google_play__stats_installs_os_version') }}"
    stats_ratings_os_version: "{{ ref('stg_google_play__stats_ratings_os_version') }}"
    stats_crashes_os_version: "{{ ref('stg_google_play__stats_crashes_os_version') }}"
    stats_installs_country: "{{ ref('stg_google_play__stats_installs_country') }}"
    stats_ratings_country: "{{ ref('stg_google_play__stats_ratings_country') }}"
    stats_store_performance_country: "{{ ref('stg_google_play__store_performance_country') }}"
    stats_store_performance_traffic_source: "{{ ref('stg_google_play__store_performance_source') }}"
    stats_installs_overview: "{{ ref('stg_google_play__stats_installs_overview') }}"
    stats_crashes_overview: "{{ ref('stg_google_play__stats_crashes_overview') }}"
    stats_ratings_overview: "{{ ref('stg_google_play__stats_ratings_overview') }}"
    earnings: "{{ ref('stg_google_play__earnings') }}"
    financial_stats_subscriptions_country: "{{ ref('stg_google_play__subscriptions_country') }}"
    country_codes: "{{ ref('google_play__country_codes') }}"
models:
  google_play:
    +schema: google_play
    +materialized: table
    intermediate:
      +materialized: ephemeral
      int_google_play__earnings:
        +materialized: view