version: 2

sources:
  - name: main
    database: tidal-cipher-381616
    schema: divvy_data_raw
    tables:
      - name: divvy_data
        description: "Raw data of Divvy bike trips in the Chicago Metropolitan area, covering rides from 2020 to 2023."


models:
  - name: stg_divvy_data
    description: |
      This model processes the raw Divvy bike trip data to provide clean and structured data for analysis. It includes information on bike ride details, timestamps, station information, and geospatial data for trips made by annual and non-annual subscribers in the Chicago Metropolitan area.
    
    columns:
      - name: r_id
        description: "A surrogate key created by concatenating ride ID and started_at timestamp."
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: ride_id
        description: "The unique identifier for each bike ride as provided by the source data."
        tests:
          - not_null

      - name: rideable_type
        description: "The type of bike used for the ride (e.g., Docked, Classic, Electric)."
      
      - name: membership_status
        description: "The user's membership status, either annual subscriber ('member') or non-annual ('casual')."

      - name: started_at
        description: "The timestamp indicating when the ride started."
        tests:
          - not_null

      - name: ended_at
        description: "The timestamp indicating when the ride ended."
        tests:
          - not_null

      - name: start_station_name
        description: "The name of the station where the ride started."
        tests:
          - not_null

      - name: start_station_id
        description: "The unique identifier of the start station."

      - name: end_station_name
        description: "The name of the station where the ride ended."
        tests:
          - not_null

      - name: end_station_id
        description: "The unique identifier of the end station."

      - name: start_lat
        description: "The latitude coordinate of the start station."

      - name: start_lng
        description: "The longitude coordinate of the start station."

      - name: end_lat
        description: "The latitude coordinate of the end station."

      - name: end_lng
        description: "The longitude coordinate of the end station."