version: 2

sources:
  - name: airbnb
    schema: main
    tables:
      - name: hosts
        identifier: raw_hosts

      - name: listings
        identifier: raw_listings

      - name: reviews
        identifier: raw_reviews
        