config-version: 2
name: 'salesforce'
version: '1.1.1'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  salesforce:
    materialized: table
    intermediate:
      materialized: ephemeral
  salesforce_source:
    materialized: table
    intermediate:
      materialized: ephemeral

profile: salesforce

vars:
  # enable history models when generating docs!
  salesforce__task_enabled: true
  salesforce__event_enabled: true
  salesforce__lead_enabled: true
  salesforce__contact_history_enabled: true
  salesforce__account_history_enabled: true
  salesforce__opportunity_history_enabled: true

  salesforce_source:
    salesforce_schema: main
    salesforce_history_schema: main

    salesforce_account_identifier: "sf_account_data"
    salesforce_opportunity_identifier: "sf_opportunity_data"
    salesforce_user_identifier: "sf_user_data"
    salesforce_user_role_identifier: "sf_user_role_data"
    salesforce_contact_identifier: "sf_contact_data"
    salesforce_lead_identifier: "sf_lead_data"
    salesforce_task_identifier: "sf_task_data"
    salesforce_event_identifier: "sf_event_data"
    salesforce_product_2_identifier: "sf_product_2_data"
    salesforce_order_identifier: "sf_order_data"
    salesforce_opportunity_line_item_identifier: "sf_opportunity_line_item_data"

    ##history mode identifiers
    salesforce_account_history_identifier: "sf_account_history_data"
    salesforce_contact_history_identifier: "sf_contact_history_data"
    salesforce_opportunity_history_identifier: "sf_opportunity_history_data"

  account: "{{ ref('stg_salesforce__account') }}"
  opportunity: "{{ ref('stg_salesforce__opportunity') }}"
  user: "{{ ref('stg_salesforce__user') }}"
  user_role: "{{ ref('stg_salesforce__user_role') }}"
  contact: "{{ ref('stg_salesforce__contact') }}"
  lead: "{{ ref('stg_salesforce__lead') }}"
  task: "{{ ref('stg_salesforce__task') }}"
  event: "{{ ref('stg_salesforce__event') }}"
  product_2: "{{ ref('stg_salesforce__product_2') }}"
  order: "{{ ref('stg_salesforce__order') }}"
  opportunity_line_item: "{{ ref('stg_salesforce__opportunity_line_item') }}"

  account_history: "{{ ref('stg_salesforce__account_history') }}"
  contact_history: "{{ ref('stg_salesforce__contact_history') }}"
  opportunity_history: "{{ ref('stg_salesforce__opportunity_history') }}"
  
  salesforce__account_pass_through_columns: 
    - name: "salesforce__account_field"
      alias: "renamed_field"
      transform_sql: "cast(renamed_field as string)"
  salesforce__contact_pass_through_columns: 
    - name: "salesforce__contact_field"
      alias: "contact_field_x"
  salesforce__event_pass_through_columns: 
    - name: "salesforce__event_field"
      transform_sql: "cast(salesforce__event_field as int64)"
  salesforce__lead_pass_through_columns: 
    - name: "salesforce__lead_field"
  salesforce__opportunity_pass_through_columns: 
    - name: "salesforce__opportunity_field"
      alias: "opportunity_field_x"
  salesforce__opportunity_line_item_pass_through_columns: 
    - name: "salesforce__opportunity_line_item_field"
      alias: "opportunity_line_item_field_x"
    - name: "field_name_2"
  salesforce__order_pass_through_columns: 
    - name: "salesforce__order_field"
      alias: "order_field_x"
    - name: "another_field"
      alias: "field_abc"
  salesforce__product_2_pass_through_columns: 
    - name: "salesforce__product_2_field"
      alias: "product_2_field_x"
  salesforce__task_pass_through_columns: 
    - name: "salesforce__task_field"
      alias: "task_field_x"
  salesforce__user_role_pass_through_columns: 
    - name: "salesforce__user_role_field"
      alias: "user_role_field_x"
  salesforce__user_pass_through_columns: 
    - name: "salesforce__user_field"


seeds:
  salesforce_integration_tests:
    +quote_columns: "{{ true if target.type in ('redshift', 'postgres') else false }}"
    +column_types:
      _fivetran_synced: timestamp
      _fivetran_active: boolean
    sf_account_data:
      +column_types:
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        annual_revenue: float
        billing_latitude: float
        billing_longitude: float
        shipping_latitude: float
        shipping_longitude: float
    sf_opportunity_data:
      +column_types:
        close_date: timestamp
        created_date: timestamp
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        amount: float
        probability: float
    sf_user_data:
      +column_types:
        last_login_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        offline_trial_expiration_date: timestamp
        latitude: float
        longitude: float
    sf_user_data:
      +column_types:
        last_login_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        offline_trial_expiration_date: timestamp
        latitude: float
        longitude: float
    sf_contact_data:
      +column_types:
        birthdate: timestamp
        created_date: timestamp
        email_bounced_date: timestamp
        last_activity_date: timestamp
        last_curequest_date: timestamp
        last_cuupdate_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_lead_data:
      +column_types:
        converted_date: timestamp
        created_date: timestamp
        email_bounced_date: timestamp
        last_activity_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_task_data:
      +column_types:
        activity_date: timestamp
        completed_date_time: timestamp
        created_date: timestamp
        last_modified_date: timestamp
        recurrence_end_date_only: timestamp
        recurrence_start_date_only: timestamp
        reminder_date_time: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_event_data:
      +column_types:
        activity_date: timestamp
        activity_date_time: timestamp
        created_date: timestamp
        end_date: timestamp
        end_date_time: timestamp
        last_modified_date   : timestamp
        recurrence_2_pattern_start_date   : timestamp
        recurrence_end_date_only: timestamp
        recurrence_start_date_time: timestamp
        reminder_date_time: timestamp
        start_date_time: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_product_2_data:
      +column_types:
        created_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_order_data:
      +column_types:
        activated_date: timestamp
        created_date: timestamp
        effective_date: timestamp
        end_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        system_modstamp: timestamp
        is_deleted: boolean
    sf_opportunity_line_item_data:
      +column_types:
        created_date: timestamp
        last_modified_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        service_date: timestamp
        system_modstamp: timestamp
        is_deleted: boolean

    sf_account_history_data:
      +column_types:
        annual_revenue: float
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        annual_revenue: float
        is_deleted: boolean
    sf_contact_history_data:
      +column_types:
        birthdate: timestamp 
        last_activity_date: timestamp 
        last_modified_date: timestamp 
        last_viewed_date: timestamp
        is_deleted: boolean
    sf_opportunity_history_data:
      +column_types:
        close_date: timestamp
        created_date: timestamp
        last_activity_date: timestamp
        last_referenced_date: timestamp
        last_viewed_date: timestamp
        amount: float
        expected_revenue: float
        is_deleted: boolean

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

clean-targets:
    - target
    - dbt_modules
    - dbt_packages
