name: 'intercom_source_integration_tests'
version: '0.8.0'
profile: 'integration_tests'
config-version: 2
models:
  intercom_source:
    materialized: table
    tmp:
      materialized: view
vars:
  intercom__using_team: false
  intercom_schema: intercom_source_integration_tests
  intercom_admin_identifier: "admin_data"
  intercom_company_history_identifier: "company_history_data"
  intercom_company_tag_history_identifier: "company_tag_history_data"
  intercom_contact_company_history_identifier: "contact_company_history_data"
  intercom_contact_history_identifier: "contact_history_data"
  intercom_contact_tag_history_identifier: "contact_tag_history_data"
  intercom_conversation_contact_history_identifier: "conversation_contact_history_data"
  intercom_conversation_history_identifier: "conversation_history_data"
  intercom_conversation_part_history_identifier: "conversation_part_history_data"
  intercom_conversation_tag_history_identifier: "conversation_tag_history_data"
  intercom_tag_identifier: "tag_data"
  intercom_team_admin_identifier: "team_admin_data"
  intercom_team_identifier: "team_data"

seeds:
  +quote_columns: "{{ true if target.type in ('redshift','postgres') else false }}"
  intercom_source_integration_tests:
    +column_types: 
      _fivetran_synced: timestamp
      _fivetran_start: timestamp
      _fivetran_end: timestamp
      _fivetran_active: boolean
    admin_data:
      +column_types:
        id: "{{ 'varchar(100)' if target.type in ('redshift','postgres') else 'string' }}"
    company_history_data:
      +column_types:
        created_at: timestamp
        updated_at: timestamp
    company_tag_history_data:
      +column_types:
        company_updated_at: timestamp
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    contact_company_history_data:
      +column_types:
        contact_updated_at: timestamp
    contact_history_data:
      +column_types:
        created_at: timestamp
        signed_up_at: timestamp
        last_replied_at: timestamp
        last_contacted_at: timestamp
        last_email_clicked_at: timestamp
        last_email_opened_at: timestamp
    contact_tag_history_data:
      +column_types:
        contact_updated_at: timestamp
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    conversation_contact_history_data:
      +column_types:
        conversation_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        conversation_updated_at: timestamp
    conversation_history_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        first_contact_reply_created_at: timestamp
        updated_at: timestamp
        waiting_since: timestamp
        snoozed_until: timestamp
    conversation_part_history_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        conversation_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        author_id: "{{ 'varchar(100)' if target.type in ('redshift','postgres') else 'string' }}"
        created_at: timestamp
        conversation_updated_at: timestamp
        updated_at: timestamp
    conversation_tag_history_data:
      +column_types:
        conversation_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        conversation_updated_at: timestamp
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    tag_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    team_admin_data:
      +column_types:
        admin_id: "{{ 'varchar(100)'  if target.type in ('redshift','postgres') else 'string'}}"
        team_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    team_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"


dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']