name: 'intercom_source'
version: '0.8.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  intercom_source:
    +schema: stg_intercom
    materialized: table
    tmp:
      materialized: view
vars:
  intercom_source:
    admin: "{{ source('intercom','admin') }}"
    company_history: "{{ source('intercom','company_history') }}"
    company_tag_history: "{{ source('intercom','company_tag_history') }}"
    contact_company_history: "{{ source('intercom','contact_company_history') }}"
    contact_history: "{{ source('intercom','contact_history') }}"
    contact_tag_history: "{{ source('intercom','contact_tag_history') }}"
    conversation_contact_history: "{{ source('intercom','conversation_contact_history') }}"
    conversation_history: "{{ source('intercom','conversation_history') }}"
    conversation_part_history: "{{ source('intercom','conversation_part_history') }}"
    conversation_tag_history: "{{ source('intercom','conversation_tag_history') }}"
    tag: "{{ source('intercom','tag') }}"
    team_admin: "{{ source('intercom','team_admin') }}"
    team: "{{ source('intercom','team') }}"
    intercom__using_contact_company: true
    intercom__using_company_tags: true
    intercom__using_contact_tags: true
    intercom__using_conversation_tags: true
    intercom__using_team: true
    intercom__company_history_pass_through_columns: []
    intercom__contact_history_pass_through_columns: []
    intercom__conversation_history_pass_through_columns: []
clean-targets:
- target
- dbt_modules
- dbt_packages
