
version: 2

models:
  - name: user_watched_movies
    description: |
      This model creates a relationship between users and the movies they have watched from the MovieLens dataset. 
      It joins the MovieLens dataset with the OMDB dataset based on movie titles, considering only the English language movies.
      The movie titles from the MovieLens dataset have the release year stripped and are then matched with the OMDB dataset 
      using a partial title match in English (ISO 639-1 language code 'en').

    refs:
      - name: movielens_ratings
      - name: movielens_movies
      - name: all_movie_aliases_iso

    columns:
      - name: user_id
        description: |
          The unique identifier for each user. It is created by concatenating 'u_' with the user's MovieLens ID. 
          The user information is extracted from the MovieLens ratings data.
        tests:
          - not_null

      - name: rating
        description: |
          The rating given by the user to the movie, extracted from the MovieLens ratings dataset. 
          This value reflects how much the user liked the movie.
        tests:
          - not_null

      - name: title
        description: |
          The title of the movie, extracted from the MovieLens dataset. The release year is removed from the movie title 
          using a regular expression to focus on the title for matching purposes.
      
      - name: OMDB_movie_id
        description: |
          The unique identifier for the movie from the OMDB dataset. The movie is matched by comparing the title from 
          the MovieLens dataset with the title from the OMDB dataset. Only movies with the English language code 'en' 
          (ISO 639-1) are considered for the match.
        tests:
          - not_null

      - name: movielens_genres
        description: |
          The genres of the movie, as categorized in the MovieLens dataset. Each movie can belong to multiple genres, 
          and these are listed as a pipe-separated string.
  - name: directed_by
    description: "The edges between movies and directors"
    columns:
      - name: movie_id
        description: "movie id"
        tests:
          - not_null
      - name: person_id
        description: "director's person id"
        tests:
          - not_null
  - name: acted_by
    description: "The edges between movies and actors"
    columns:
      - name: movie_id
        description: "movie id"
        tests:
          - not_null
      - name: person_id
        description: "actor's person id"
        tests:
          - not_null
  - name: with_genre
    description: "The edges between movies and genres"
    columns:
      - name: movie_id
        description: "movie id"
        tests:
          - not_null
      - name: genre_id
        description: "genre id"
        tests:
          - not_null
  - name: people
    description: "People in the movie database"
    columns:
      - name: person_id
        description: "person id"
        tests:
          - not_null
      - name: name
        description: "person's name"
        tests:
          - not_null
      - name: birthdate
        description: "person's birth date"
        tests:
          - not_null
      - name: gender
        description: "person's gender"
  - name: genres
    description: "Genres in the movie database"
    columns:
      - name: genre_id
        description: "genre id"
        tests:
          - not_null
      - name: genre_name
        description: "genre name"
        tests:
          - not_null
  - name: movies
    description: "Movies in the movie database"
    columns:
      - name: movie_id
        description: "movie id"
        tests:
          - not_null
      - name: movie_name
        description: "movie title"
        tests:
          - not_null
