name: 'google_play'
version: '0.4.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: 'google_play'

vars:

  google_play_schema: main
  google_play_source:
    google_play_stats_installs_app_version_identifier: "stats_installs_app_version"
    google_play_stats_crashes_app_version_identifier: "stats_crashes_app_version"
    google_play_stats_ratings_app_version_identifier: "stats_ratings_app_version"
    google_play_stats_installs_device_identifier: "stats_installs_device"
    google_play_stats_ratings_device_identifier: "stats_ratings_device"
    google_play_stats_installs_os_version_identifier: "stats_installs_os_version"
    google_play_stats_ratings_os_version_identifier: "stats_ratings_os_version"
    google_play_stats_crashes_os_version_identifier: "stats_crashes_os_version"
    google_play_stats_installs_country_identifier: "stats_installs_country"
    google_play_stats_ratings_country_identifier: "stats_ratings_country"
    google_play_stats_store_performance_country_identifier: "stats_store_performance_country"
    google_play_stats_store_performance_traffic_source_identifier: "stats_store_performance_traffic_source"
    google_play_stats_installs_overview_identifier: "stats_installs_overview"
    google_play_stats_crashes_overview_identifier: "stats_crashes_overview"
    google_play_stats_ratings_overview_identifier: "stats_ratings_overview"
    google_play_earnings_identifier: "earnings"
    google_play_financial_stats_subscriptions_country_identifier: "financial_stats_subscriptions_country"

  google_play:
    stats_installs_app_version: "{{ ref('stg_google_play__stats_installs_app_version') }}"
    stats_crashes_app_version: "{{ ref('stg_google_play__stats_crashes_app_version') }}"
    stats_ratings_app_version: "{{ ref('stg_google_play__stats_ratings_app_version') }}"
    stats_installs_device: "{{ ref('stg_google_play__stats_installs_device') }}"
    stats_ratings_device: "{{ ref('stg_google_play__stats_ratings_device') }}"
    stats_installs_os_version: "{{ ref('stg_google_play__stats_installs_os_version') }}"
    stats_ratings_os_version: "{{ ref('stg_google_play__stats_ratings_os_version') }}"
    stats_crashes_os_version: "{{ ref('stg_google_play__stats_crashes_os_version') }}"
    stats_installs_country: "{{ ref('stg_google_play__stats_installs_country') }}"
    stats_ratings_country: "{{ ref('stg_google_play__stats_ratings_country') }}"
    stats_store_performance_country: "{{ ref('stg_google_play__store_performance_country') }}"
    stats_store_performance_traffic_source: "{{ ref('stg_google_play__store_performance_source') }}"
    stats_installs_overview: "{{ ref('stg_google_play__stats_installs_overview') }}"
    stats_crashes_overview: "{{ ref('stg_google_play__stats_crashes_overview') }}"
    stats_ratings_overview: "{{ ref('stg_google_play__stats_ratings_overview') }}"
    earnings: "{{ ref('stg_google_play__earnings') }}"
    financial_stats_subscriptions_country: "{{ ref('stg_google_play__subscriptions_country') }}"
    country_codes: "{{ ref('google_play__country_codes') }}"
models:
  +materialized: table
seeds:
  google_play_source:
    +column_types:
      country_name: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      alternative_country_name: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      region: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
      sub_region: "{{ 'string' if target.type in ['bigquery','spark','databricks'] else 'varchar(255)' }}"
    stats_installs_overview:
      +column_types:
        active_device_installs: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    stats_ratings_app_version:
      +column_types:
        app_version_code: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"