version: 2

models:
  - name: dim_regional_managers
    description: >
      This model represents a dimension table for regional managers, 
      linking sales managers to the respective regions they manage.
    columns:
      - name: id
        description: "Unique identifier for each regional manager."
        tests:
          - unique
          - not_null
        type: integer
      - name: manager_name
        description: "Name of the sales manager."
        type: string
      - name: region_id
        description: "Identifier for the region the manager oversees."
        type: integer

    # Define references to source models
    refs:
      - name: stg_sales_managers
      - name: dim_regions

  - name: fct_sales
    description: >
      This fact table captures transactional sales data, including order details, 
      product, customer, shipping, and geographical information. Each entry corresponds 
      to an individual sales transaction, enhanced with dimensional data for analysis.
    columns:
      - name: id
        description: "Unique identifier for each sales transaction."
        tests:
          - unique
          - not_null
        type: integer
      - name: order_id
        description: "Unique identifier for the sales order."
        tests:
          - not_null
        type: integer
      - name: order_date_id
        description: "The date the order was placed, represented as an integer in YYYYMMDD format."
        tests:
          - not_null
        type: integer
      - name: ship_date_id
        description: "The date the order was shipped, represented as an integer in YYYYMMDD format."
        tests:
          - not_null
        type: integer
      - name: sales
        description: "The total sales amount for the transaction."
        type: float
      - name: profit
        description: "The profit generated from the transaction."
        type: float
      - name: quantity
        description: "The number of items sold in the transaction."
        type: integer
      - name: discount
        description: "The discount applied to the transaction."
        type: float
      - name: dim_products_id
        description: "The foreign key linking to the dim_products table."
        tests:
          - not_null
        type: integer
      - name: dim_customers_id
        description: "The foreign key linking to the dim_customers table."
        tests:
          - not_null
        type: integer
      - name: dim_shipping_id
        description: "The foreign key linking to the dim_shipping table."
        tests:
          - not_null
        type: integer
      - name: dim_geo_id
