config-version: 2
name: 'asana_source_integration_tests'
version: 0.8.0
profile: 'integration_tests'
vars:
  asana_schema: asana_source_integrations_tests_02
  asana_source:
    asana_user_identifier: "user_data"
    asana_project_identifier: "project_data"
    asana_task_identifier: "task_data"
    asana_story_identifier: "story_data"
    asana_team_identifier: "team_data"
    asana_tag_identifier: "tag_data"
    asana_project_task_identifier: "project_task_data"
    asana_task_follower_identifier: "task_follower_data"
    asana_task_tag_identifier: "task_tag_data"
    asana_section_identifier: "section_data"
    asana_task_section_identifier: "task_section_data"
seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  asana_source_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    user_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    project_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        owner_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        team_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        workspace_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    task_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        assignee_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        completed_by_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        parent_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        workspace_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        completed_at: "timestamp"
        created_at: "timestamp"
        due_on: "timestamp"
        due_at: "timestamp"
        modified_at: "timestamp"
        start_on: "timestamp"
        _fivetran_synced: "timestamp"
    story_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_by_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        target_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    team_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        organization_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    tag_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        workspace_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    project_task_data:
      +column_types:
        project_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        task_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    task_follower_data:
      +column_types:
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        task_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    task_tag_data:
      +column_types:
        tag_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        task_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    section_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        project_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    task_section_data:
      +column_types:
        section_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        task_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']