{% macro get_pa0007_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_rowid", "datatype": dbt.type_numeric()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "aedtm", "datatype": dbt.type_string()},
    {"name": "arbst", "datatype": dbt.type_numeric()},
    {"name": "awtyp", "datatype": dbt.type_string()},
    {"name": "begda", "datatype": dbt.type_string()},
    {"name": "dysch", "datatype": dbt.type_string()},
    {"name": "empct", "datatype": dbt.type_numeric()},
    {"name": "endda", "datatype": dbt.type_string()},
    {"name": "flag1", "datatype": dbt.type_string()},
    {"name": "flag2", "datatype": dbt.type_string()},
    {"name": "flag3", "datatype": dbt.type_string()},
    {"name": "flag4", "datatype": dbt.type_string()},
    {"name": "grpvl", "datatype": dbt.type_string()},
    {"name": "histo", "datatype": dbt.type_string()},
    {"name": "itbld", "datatype": dbt.type_string()},
    {"name": "itxex", "datatype": dbt.type_string()},
    {"name": "jrstd", "datatype": dbt.type_numeric()},
    {"name": "kztim", "datatype": dbt.type_string()},
    {"name": "mandt", "datatype": dbt.type_string()},
    {"name": "maxja", "datatype": dbt.type_numeric()},
    {"name": "maxmo", "datatype": dbt.type_numeric()},
    {"name": "maxta", "datatype": dbt.type_numeric()},
    {"name": "maxwo", "datatype": dbt.type_numeric()},
    {"name": "minja", "datatype": dbt.type_numeric()},
    {"name": "minmo", "datatype": dbt.type_numeric()},
    {"name": "minta", "datatype": dbt.type_numeric()},
    {"name": "minwo", "datatype": dbt.type_numeric()},
    {"name": "mostd", "datatype": dbt.type_numeric()},
    {"name": "objps", "datatype": dbt.type_string()},
    {"name": "ordex", "datatype": dbt.type_string()},
    {"name": "pernr", "datatype": dbt.type_string()},
    {"name": "preas", "datatype": dbt.type_string()},
    {"name": "refex", "datatype": dbt.type_string()},
    {"name": "rese1", "datatype": dbt.type_string()},
    {"name": "rese2", "datatype": dbt.type_string()},
    {"name": "schkz", "datatype": dbt.type_string()},
    {"name": "seqnr", "datatype": dbt.type_string()},
    {"name": "sprps", "datatype": dbt.type_string()},
    {"name": "subty", "datatype": dbt.type_string()},
    {"name": "teilk", "datatype": dbt.type_string()},
    {"name": "uname", "datatype": dbt.type_string()},
    {"name": "wkwdy", "datatype": dbt.type_numeric()},
    {"name": "wostd", "datatype": dbt.type_numeric()},
    {"name": "wweek", "datatype": dbt.type_string()},
    {"name": "zterf", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}