name: 'linkedin_pages_source_integration_tests'
version: '0.3.0'
profile: 'integration_tests'
config-version: 2

vars:
  linkedin_pages_source:
    linkedin_pages_organization_identifier: "linkedin_pages_organization_data"
    linkedin_pages_organization_ugc_post_identifier: "linkedin_pages_organization_ugc_post_data"
    linkedin_pages_share_statistic_identifier: "linkedin_pages_share_statistic_data"
    linkedin_pages_post_content_identifier: "linkedin_pages_post_content_data"
    linkedin_pages_ugc_post_history_identifier: "linkedin_pages_ugc_post_history_data"
    linkedin_pages_ugc_post_share_statistic_identifier: "linkedin_pages_ugc_post_share_statistic_data"
    linkedin_pages_schema: linkedin_pgs_source_integrations_tests_2

seeds:
  linkedin_pages_source_integration_tests:
    linkedin_pages_ugc_post_share_statistic_data:
      +column_types:
        ugc_post_id: "{%- if target.type == 'bigquery' -%} INT64 {%- else -%} bigint {%- endif -%}"
