name: 'instagram_business'
version: '0.2.1'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  media_history_staging: "{{ ref('stg_instagram_business__media_history') }}"
  media_insights_staging: "{{ ref('stg_instagram_business__media_insights') }}"
  user_history_staging: "{{ ref('stg_instagram_business__user_history') }}"
models:
  instagram_business:
    +schema: instagram_business
    +materialized: table
