name: 'linkedin_pages'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  share_statistic_staging: "{{ ref('stg_linkedin_pages__share_statistic') }}"
  ugc_post_share_statistic_staging: "{{ ref('stg_linkedin_pages__ugc_post_share_statistic') }}"
  ugc_post_history_staging: "{{ ref('stg_linkedin_pages__ugc_post_history') }}"
  post_content: "{{ ref('stg_linkedin_pages__post_content') }}"
  organization_staging: "{{ ref('stg_linkedin_pages__organization') }}"
  organization_ugc_post_staging: "{{ ref('stg_linkedin_pages__organization_ugc_post') }}"
models:
  linkedin_pages:
    +schema: linkedin_pages
    +materialized: table
