name: 'hubspot_source_integration_tests'
version: '0.15.0'
profile: 'integration_tests'
config-version: 2

models:
  +schema: "{{ 'hubspot_sqlw_tests' if target.name == 'databricks-sql' else 'hubspot' }}"
  # +schema: "hubspot_{{ var('directed_schema','dev') }}" ## To be used for validation testing

vars:
  hubspot_schema: hubspot_source_integration_tests_21
  hubspot_source:
    hubspot_service_enabled: true
    # hubspot_sales_enabled: true # enable when generating docs
    # hubspot_marketing_enabled: true # enable when generating docs
    # hubspot_contact_merge_audit_enabled: true # enable when generating docs
    # hubspot_using_all_email_events: true # enable when generating docs
    # hubspot_merged_deal_enabled: true # enable when generating docs  
    hubspot_company_property_history_identifier: "company_property_history_data"
    hubspot_company_identifier: "company_data"
    hubspot_contact_identifier: "contact_data"
    hubspot_contact_merge_audit_identifier: "contact_merge_audit_data"
    hubspot_contact_list_member_identifier: "contact_list_member_data"
    hubspot_contact_property_history_identifier: "contact_property_history_data"
    hubspot_deal_identifier: "deal_data"
    hubspot_deal_stage_identifier: "deal_stage_data"
    hubspot_deal_company_identifier: "deal_company_data"
    hubspot_deal_contact_identifier: "deal_contact_data"
    hubspot_deal_pipeline_identifier: "deal_pipeline_data"
    hubspot_deal_pipeline_stage_identifier: "deal_pipeline_stage_data"
    hubspot_deal_property_history_identifier: "deal_property_history_data"
    hubspot_email_campaign_identifier: "email_campaign_data"
    hubspot_email_event_identifier: "email_event_data"
    hubspot_email_event_bounce_identifier: "email_event_bounce_data"
    hubspot_email_event_click_identifier: "email_event_click_data"
    hubspot_email_event_deferred_identifier: "email_event_deferred_data"
    hubspot_email_event_delivered_identifier: "email_event_delivered_data"
    hubspot_email_event_forward_identifier: "email_event_forward_data"
    hubspot_email_event_open_identifier: "email_event_open_data"
    hubspot_email_event_print_identifier: "email_event_print_data"
    hubspot_email_event_spam_report_identifier: "email_event_spam_report_data"
    hubspot_email_event_status_change_identifier: "email_event_status_change_data"
    hubspot_engagement_identifier: "engagement_data"
    hubspot_engagement_call_identifier: "engagement_call_data"
    hubspot_engagement_company_identifier: "engagement_company_data"
    hubspot_engagement_contact_identifier: "engagement_contact_data"
    hubspot_engagement_deal_identifier: "engagement_deal_data"
    hubspot_engagement_email_identifier: "engagement_email_data"
    hubspot_engagement_meeting_identifier: "engagement_meeting_data"
    hubspot_engagement_note_identifier: "engagement_note_data"
    hubspot_engagement_task_identifier: "engagement_task_data"
    hubspot_owner_identifier: "owner_data"
    hubspot_property_identifier: "property_data"
    hubspot_property_option_identifier: "property_option_data"
    hubspot_ticket_company_identifier: "ticket_company_data"
    hubspot_ticket_contact_identifier: "ticket_contact_data"
    hubspot_ticket_deal_identifier: "ticket_deal_data"
    hubspot_ticket_engagement_identifier: "ticket_engagement_data"
    hubspot_ticket_pipeline_identifier: "ticket_pipeline_data"
    hubspot_ticket_pipeline_stage_identifier: "ticket_pipeline_stage_data"
    hubspot_ticket_property_history_identifier: "ticket_property_history_data"
    hubspot_ticket_identifier: "ticket_data"
    hubspot_contact_list_identifier: "contact_list_data"
    hubspot_email_event_sent_identifier: "email_event_sent_data"
    hubspot_email_event_dropped_identifier: "email_event_dropped_data"
    hubspot_merged_deal_identifier: "merged_deal_data"

seeds:
  hubspot_source_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    owner_data:
      +column_types:
        owner_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    company_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    deal_data:
      +column_types:
        deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        owner_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: timestamp
        property_closedate: timestamp
        property_createdate: timestamp
    deal_contact_data:
      +column_types:
        contact_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    deal_stage_data:
      +column_types:
        deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    company_property_history_data:
      +column_types:
        company_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    email_campaign_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        content_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    deal_property_history_data:
      +column_types:
        deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    engagement_call_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: timestamp
        property_hs_createdate: timestamp
        property_hs_timestamp: timestamp
    engagement_company_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        company_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    engagement_contact_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        contact_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    engagement_deal_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    engagement_data:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    engagement_meeting_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: timestamp
        property_hs_createdate: timestamp
        property_hs_timestamp: timestamp
    engagement_email_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: timestamp
        property_hs_createdate: timestamp
        property_hs_timestamp: timestamp
    engagement_task_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        property_hs_object_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: timestamp
        property_hs_createdate: timestamp
        property_hs_timestamp: timestamp
    engagement_note_data:
      +column_types:
        engagement_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        _fivetran_synced: timestamp
        property_hs_createdate: timestamp
        property_hs_timestamp: timestamp
    deal_pipeline_data:
      +column_types:
        pipeline_id: "{{ 'varchar(100)'  if target.type in ('redshift','postgres') else 'string'}}"
    deal_pipeline_stage_data:
      +column_types:
        stage_id: "{{ 'varchar(100)'  if target.type in ('redshift','postgres') else 'string'}}"
    email_event_sent_data_snowflake:
      +alias: email_event_sent_data
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    email_event_sent_data_postgres:
      +alias: email_event_sent_data
      +enabled: "{{ true if target.type == 'postgres' else false }}"
    email_event_sent_data:
      +enabled: "{{ true if target.type not in ('snowflake', 'postgres') else false }}"
    email_event_dropped_data_snowflake:
      +alias: email_event_dropped_data
      +enabled: "{{ true if target.type == 'snowflake' else false }}"
    email_event_dropped_data_postgres:
      +alias: email_event_dropped_data
      +enabled: "{{ true if target.type == 'postgres' else false }}"
    email_event_dropped_data:
      +enabled: "{{ true if target.type not in ('snowflake', 'postgres') else false }}"
    contact_list_data:
      +enabled: "{{ true if target.type != 'postgres' else false }}"
    contact_list_data_postgres:
      +alias: contact_list_data
      +enabled: "{{ true if target.type == 'postgres' else false }}"
    email_event_data: 
      +column_types:
        _fivetran_synced: timestamp
        caused_by_created: timestamp
        created: timestamp
        obsoleted_by_created: timestamp
        sent_by_created: timestamp
    merged_deal_data:
      +column_types:
        deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        merged_deal_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']