version: 2

models:

  - name: lost_revenue
    description: |
      This model calculates the revenue lost due to returned items for each customer by analyzing their orders and returns. 
      It joins customer data with orders and line items to sum the revenue lost from returned items, providing additional customer details such as account balance, phone number, and address.

    sources:
      - name: TPCH_SF1
        tables:
          - name: orders
          - name: customer
          - name: lineitem
          - name: nation

    columns:
      - name: c_custkey
        description: "The unique identifier for the customer."
        tests:
          - not_null
          - unique

      - name: c_name
        description: "The name of the customer."

      - name: revenue_lost
        description: "The total amount of revenue lost due to returned items."

      - name: c_acctbal
        description: "The account balance of the customer."

      - name: n_name
        description: "The name of the nation the customer is associated with."

      - name: c_address
        description: "The address of the customer."

      - name: c_phone
        description: "The phone number of the customer."

      - name: c_comment
        description: "Additional comments or notes associated with the customer."


  - name: client_purchase_status
    description: |
      This model calculates the purchase status of each customer by analyzing their total purchases, returns, and lifetime value. 
      It categorizes customers based on the percentage of revenue lost due to returns and assigns a status color to indicate customer health (green, yellow, orange, red).
      
    refs:
      - name: order_line_items
      - name: lost_revenue

    sources:
      - name: TPCH_SF1
        tables:
          - name: customer

    columns:
      - name: customer_id
        description: "The unique identifier for each customer."
        tests:
          - not_null
          - unique

      - name: customer_name
        description: "The name of the customer."

      - name: purchase_total
        description: "The total amount of purchases made by the customer."

      - name: return_total
        description: "The total amount of revenue lost due to returned items."

      - name: lifetime_value
        description: "The net lifetime value of the customer, calculated as the total purchases minus total returns."

      - name: return_pct
        description: "The percentage of total purchases lost due to returns."

      - name: customer_status
        description: "The status color representing the customer's health based on their return percentage (green, yellow, orange, red)."
        tests:
          - accepted_values:
              values: ['green', 'yellow', 'orange', 'red']
