{% macro get_worker_position_history_columns() %}

{% set columns = [
    {"name": "_fivetran_active", "datatype": dbt.type_boolean()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "_fivetran_start", "datatype": dbt.type_timestamp()},
    {"name": "_fivetran_end", "datatype": dbt.type_timestamp()},
    {"name": "academic_pay_setup_data_annual_work_period_end_date", "datatype": "date"},
    {"name": "academic_pay_setup_data_annual_work_period_start_date", "datatype": "date"},
    {"name": "academic_pay_setup_data_annual_work_period_work_percent_of_year", "datatype": dbt.type_float()},
    {"name": "academic_pay_setup_data_disbursement_plan_period_end_date", "datatype": "date"},
    {"name": "academic_pay_setup_data_disbursement_plan_period_start_date", "datatype": "date"},
    {"name": "business_site_summary_display_language", "datatype": dbt.type_string()},
    {"name": "business_site_summary_local", "datatype": dbt.type_string()},
    {"name": "business_site_summary_location", "datatype": dbt.type_string()},
    {"name": "business_site_summary_location_type", "datatype": dbt.type_string()},
    {"name": "business_site_summary_name", "datatype": dbt.type_string()},
    {"name": "business_site_summary_scheduled_weekly_hours", "datatype": dbt.type_float()},
    {"name": "business_site_summary_time_profile", "datatype": dbt.type_string()},
    {"name": "business_title", "datatype": dbt.type_string()},
    {"name": "critical_job", "datatype": dbt.type_boolean()},
    {"name": "default_weekly_hours", "datatype": dbt.type_float()},
    {"name": "difficulty_to_fill", "datatype": dbt.type_string()},
    {"name": "effective_date", "datatype": "date"},
    {"name": "employee_type", "datatype": dbt.type_string()},
    {"name": "end_date", "datatype": "date"},
    {"name": "end_employment_date", "datatype": "date"},
    {"name": "exclude_from_head_count", "datatype": dbt.type_boolean()},
    {"name": "expected_assignment_end_date", "datatype": "date"},
    {"name": "external_employee", "datatype": dbt.type_string()},
    {"name": "federal_withholding_fein", "datatype": dbt.type_string()},
    {"name": "frequency", "datatype": dbt.type_string()},
    {"name": "full_time_equivalent_percentage", "datatype": dbt.type_float()},
    {"name": "headcount_restriction_code", "datatype": dbt.type_string()},
    {"name": "home_country", "datatype": dbt.type_string()},
    {"name": "host_country", "datatype": dbt.type_string()},
    {"name": "international_assignment_type", "datatype": dbt.type_string()},
    {"name": "is_primary_job", "datatype": dbt.type_boolean()},
    {"name": "job_exempt", "datatype": dbt.type_boolean()},
    {"name": "job_profile_id", "datatype": dbt.type_string()},
    {"name": "management_level_code", "datatype": dbt.type_string()},
    {"name": "paid_fte", "datatype": dbt.type_float()},
    {"name": "pay_group", "datatype": dbt.type_string()},
    {"name": "pay_rate", "datatype": dbt.type_string()},
    {"name": "pay_rate_type", "datatype": dbt.type_string()},
    {"name": "pay_through_date", "datatype": "date"},
    {"name": "payroll_entity", "datatype": dbt.type_string()},
    {"name": "payroll_file_number", "datatype": dbt.type_string()},
    {"name": "position_id", "datatype": dbt.type_string()},
    {"name": "regular_paid_equivalent_hours", "datatype": dbt.type_float()},
    {"name": "scheduled_weekly_hours", "datatype": dbt.type_float()},
    {"name": "specify_paid_fte", "datatype": dbt.type_boolean()},
    {"name": "specify_working_fte", "datatype": dbt.type_boolean()},
    {"name": "start_date", "datatype": "date"},
    {"name": "start_international_assignment_reason", "datatype": dbt.type_string()},
    {"name": "work_hours_profile", "datatype": dbt.type_string()},
    {"name": "work_shift", "datatype": dbt.type_string()},
    {"name": "work_shift_required", "datatype": dbt.type_boolean()},
    {"name": "work_space", "datatype": dbt.type_string()},
    {"name": "worker_hours_profile_classification", "datatype": dbt.type_string()},
    {"name": "worker_id", "datatype": dbt.type_string()},
    {"name": "working_fte", "datatype": dbt.type_float()},
    {"name": "working_time_frequency", "datatype": dbt.type_string()},
    {"name": "working_time_unit", "datatype": dbt.type_string()},
    {"name": "working_time_value", "datatype": dbt.type_float()}
] %}

{{ return(columns) }}

{% endmacro %}
