name: 'apple_store'
version: '0.4.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]


profile: 'apple_store'

vars:
  apple_store_schema: main
  apple_store_source:
    apple_store_app_identifier: "app"
    apple_store_app_store_platform_version_source_type_report_identifier: "app_store_platform_version_source_type"
    apple_store_app_store_source_type_device_report_identifier: "app_store_source_type_device"
    apple_store_app_store_territory_source_type_report_identifier: "app_store_territory_source_type"
    apple_store_crashes_app_version_device_report_identifier: "crashes_app_version"
    apple_store_crashes_platform_version_device_report_identifier: "crashes_platform_version"
    apple_store_downloads_platform_version_source_type_report_identifier: "downloads_platform_version_source_type"
    apple_store_downloads_source_type_device_report_identifier: "downloads_source_type_device"
    apple_store_downloads_territory_source_type_report_identifier: "downloads_territory_source_type"
    apple_store_sales_account_identifier: "sales_account"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_events"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_usage_app_version_source_type_report_identifier: "usage_app_version_source_type"
    apple_store_usage_platform_version_source_type_report_identifier: "usage_platform_version_source_type"
    apple_store_usage_source_type_device_report_identifier: "usage_source_type_device"
    apple_store_usage_territory_source_type_report_identifier: "usage_territory_source_type"
    apple_store__subscription_events:
      - 'Renew'
      - 'Cancel'
      - 'Subscribe'

  app: "{{ ref('stg_apple_store__app') }}"
  app_store_device: "{{ ref('stg_apple_store__app_store_device') }}"
  usage_device: "{{ ref('stg_apple_store__usage_device') }}"
  downloads_device: "{{ ref('stg_apple_store__downloads_device') }}"
  app_store_territory: "{{ ref('stg_apple_store__app_store_territory') }}"
  downloads_territory: "{{ ref('stg_apple_store__downloads_territory') }}"
  usage_territory: "{{ ref('stg_apple_store__usage_territory') }}"
  app_store_platform_version: "{{ ref('stg_apple_store__app_store_platform_version') }}"
  crashes_platform_version: "{{ ref('stg_apple_store__crashes_platform_version') }}"
  downloads_platform_version: "{{ ref('stg_apple_store__downloads_platform_version') }}"
  usage_platform_version: "{{ ref('stg_apple_store__usage_platform_version') }}"
  crashes_app_version: "{{ ref('stg_apple_store__crashes_app_version') }}"
  usage_app_version: "{{ ref('stg_apple_store__usage_app_version') }}"
  sales_account: "{{ ref('stg_apple_store__sales_account') }}"
  sales_subscription_events: "{{ ref('stg_apple_store__sales_subscription_events') }}"
  sales_subscription_summary: "{{ ref('stg_apple_store__sales_subscription_summary') }}"
  apple_store_country_codes: "{{ ref('apple_store_country_codes') }}"
  apple_store__subscription_events:
  - 'Renew'
  - 'Cancel'
  - 'Subscribe'

models:
    materialized: table
    intermediate:
      +materialized: ephemeral
