contact_links:
  - name: Ask a question during our office hours
    url: https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours
    about: Schedule time during the external office hours block with the Fivetran Analytics Engineering team for support
  - name: Fivetran connector question
    url: https://support.fivetran.com/hc
    about: Have a question about your connector? Check out the Fivetran support portal for more details.
  - name: What is dbt
    url: https://docs.getdbt.com/docs/introduction
    about: Check out the dbt docs for all dbt related information
  - name: Hang out in dbt Slack
    url: https://www.getdbt.com/community/
    about: Have a question or just want to chat with fellow data friends, join dbt Slack and hangout in the tools-fivetran channel with us!