{% macro get_daily_page_metrics_total_columns() %}

{% set columns = [
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "date", "datatype": dbt.type_timestamp()},
    {"name": "page_actions_post_reactions_anger_total", "datatype": dbt.type_int()},
    {"name": "page_actions_post_reactions_haha_total", "datatype": dbt.type_int()},
    {"name": "page_actions_post_reactions_like_total", "datatype": dbt.type_int()},
    {"name": "page_actions_post_reactions_love_total", "datatype": dbt.type_int()},
    {"name": "page_actions_post_reactions_sorry_total", "datatype": dbt.type_int()},
    {"name": "page_actions_post_reactions_total", "datatype": dbt.type_int()},
    {"name": "page_actions_post_reactions_wow_total", "datatype": dbt.type_int()},
    {"name": "page_fan_adds", "datatype": dbt.type_int()},
    {"name": "page_fan_removes", "datatype": dbt.type_int()},
    {"name": "page_fans", "datatype": dbt.type_int()},
    {"name": "page_fans_online_per_day", "datatype": dbt.type_int()},
    {"name": "page_id", "datatype": dbt.type_string()},
    {"name": "page_impressions", "datatype": dbt.type_int()},
    {"name": "page_impressions_nonviral", "datatype": dbt.type_int()},
    {"name": "page_impressions_organic", "datatype": dbt.type_int()},
    {"name": "page_impressions_paid", "datatype": dbt.type_int()},
    {"name": "page_impressions_viral", "datatype": dbt.type_int()},
    {"name": "page_negative_feedback", "datatype": dbt.type_int()},
    {"name": "page_places_checkin_total", "datatype": dbt.type_int()},
    {"name": "page_post_engagements", "datatype": dbt.type_int()},
    {"name": "page_posts_impressions", "datatype": dbt.type_int()},
    {"name": "page_posts_impressions_nonviral", "datatype": dbt.type_int()},
    {"name": "page_posts_impressions_organic", "datatype": dbt.type_int()},
    {"name": "page_posts_impressions_paid", "datatype": dbt.type_int()},
    {"name": "page_posts_impressions_viral", "datatype": dbt.type_int()},
    {"name": "page_total_actions", "datatype": dbt.type_int()},
    {"name": "page_video_complete_views_30_s", "datatype": dbt.type_int()},
    {"name": "page_video_complete_views_30_s_autoplayed", "datatype": dbt.type_int()},
    {"name": "page_video_complete_views_30_s_click_to_play", "datatype": dbt.type_int()},
    {"name": "page_video_complete_views_30_s_organic", "datatype": dbt.type_int()},
    {"name": "page_video_complete_views_30_s_paid", "datatype": dbt.type_int()},
    {"name": "page_video_complete_views_30_s_repeat_views", "datatype": dbt.type_int()},
    {"name": "page_video_repeat_views", "datatype": dbt.type_int()},
    {"name": "page_video_view_time", "datatype": dbt.type_int()},
    {"name": "page_video_views", "datatype": dbt.type_int()},
    {"name": "page_video_views_10_s", "datatype": dbt.type_int()},
    {"name": "page_video_views_10_s_autoplayed", "datatype": dbt.type_int()},
    {"name": "page_video_views_10_s_click_to_play", "datatype": dbt.type_int()},
    {"name": "page_video_views_10_s_organic", "datatype": dbt.type_int()},
    {"name": "page_video_views_10_s_paid", "datatype": dbt.type_int()},
    {"name": "page_video_views_10_s_repeat", "datatype": dbt.type_int()},
    {"name": "page_video_views_autoplayed", "datatype": dbt.type_int()},
    {"name": "page_video_views_click_to_play", "datatype": dbt.type_int()},
    {"name": "page_video_views_organic", "datatype": dbt.type_int()},
    {"name": "page_video_views_paid", "datatype": dbt.type_int()},
    {"name": "page_views_total", "datatype": dbt.type_int()}
] %}

{{ return(columns) }}

{% endmacro %}
