name: 'greenhouse_source'
version: 0.6.0
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  greenhouse_source:
    activity: "{{ source('greenhouse', 'activity') }}"
    application: "{{ source('greenhouse', 'application') }}"
    application_history: "{{ source('greenhouse', 'application_history') }}"
    attachment: "{{ source('greenhouse', 'attachment') }}"
    department: "{{ source('greenhouse', 'department') }}"
    candidate: "{{ source('greenhouse', 'candidate') }}"
    candidate_tag: "{{ source('greenhouse', 'candidate_tag') }}"
    eeoc: "{{ source('greenhouse', 'eeoc') }}"
    email_address: "{{ source('greenhouse', 'email_address') }}"
    hiring_team: "{{ source('greenhouse', 'hiring_team') }}"
    interview: "{{ source('greenhouse', 'interview') }}"
    job: "{{ source('greenhouse', 'job') }}"
    job_department: "{{ source('greenhouse', 'job_department') }}"
    job_office: "{{ source('greenhouse', 'job_office') }}"
    job_opening: "{{ source('greenhouse', 'job_opening') }}"
    job_post: "{{ source('greenhouse', 'job_post') }}"
    job_stage: "{{ source('greenhouse', 'job_stage') }}"
    job_application: "{{ source('greenhouse', 'job_application') }}"
    office: "{{ source('greenhouse', 'office') }}"
    phone_number: "{{ source('greenhouse', 'phone_number') }}"
    prospect_pool: "{{ source('greenhouse', 'prospect_pool') }}"
    prospect_stage: "{{ source('greenhouse', 'prospect_stage') }}"
    scheduled_interview: "{{ source('greenhouse', 'scheduled_interview') }}"
    scheduled_interviewer: "{{ source('greenhouse', 'scheduled_interviewer') }}"
    scorecard: "{{ source('greenhouse', 'scorecard') }}"
    scorecard_attribute: "{{ source('greenhouse', 'scorecard_attribute') }}"
    social_media_address: "{{ source('greenhouse', 'social_media_address') }}"
    source: "{{ source('greenhouse', 'source') }}"
    tag: "{{ source('greenhouse', 'tag') }}"
    user: "{{ source('greenhouse', 'user') }}"
    user_email: "{{ source('greenhouse', 'user_email') }}"
  greenhouse_using_eeoc: true
  greenhouse_using_app_history: true
  greenhouse_using_prospects: true
  greenhouse_using_job_office: true
  greenhouse_using_job_department: true
models:
  greenhouse_source:
    +materialized: table
    +schema: stg_greenhouse
    tmp:
      +materialized: view
