version: 2

sources:
  - name: main
    tables:
      - name: raw_gitcoin_passport_scores
        meta:
          dagster:
            asset_key: ["raw_gitcoin_passport_scores"]
      - name: raw_allo_projects
        meta:
          dagster:
            asset_key: ["raw_allo_projects"]
      - name: raw_allo_prices
        meta:
          dagster:
            asset_key: ["raw_allo_prices"]
      - name: raw_allo_rounds
        meta:
          dagster:
            asset_key: ["raw_allo_rounds"]
      - name: raw_allo_donations
        meta:
          dagster:
            asset_key: ["raw_allo_donations"]
      - name: raw_allo_deployments
        meta:
          dagster:
            asset_key: ["raw_allo_deployments"]
      - name: raw_allo_applications
        meta:
          dagster:
            asset_key: ["raw_allo_applications"]
      - name: raw_allo_subscriptions
        meta:
          dagster:
            asset_key: ["raw_allo_subscriptions"]
      - name: raw_chain_metadata
        meta:
          dagster:
            asset_key: ["raw_chain_metadata"]
      - name: raw_giveth_projects
        meta:
          dagster:
            asset_key: ["raw_giveth_projects"]
      - name: raw_karmahq_attestations
        meta:
          dagster:
            asset_key: ["raw_karmahq_attestations"]
