name: 'instagram_business_source'
version: '0.2.1'

config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  media_history: "{{ source('instagram_business','media_history') }}"
  media_insights: "{{ source('instagram_business','media_insights') }}"
  user_history: "{{ source('instagram_business','user_history') }}"
models:
  instagram_business_source:
    +schema: stg_instagram_business
    +materialized: table
    tmp:
      +materialized: view
