name: 'hubspot'
version: '0.18.0'

config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

profile: 'hubspot'

vars:
  hubspot_schema: main
  hubspot_service_enabled: true
  # hubspot_sales_enabled: true # enable when generating docs
  # hubspot_marketing_enabled: true # enable when generating docs
  # hubspot_contact_merge_audit_enabled: true # enable when generating docs
  # hubspot_using_all_email_events: true # enable when generating docs
  # hubspot_merged_deal_enabled: true # enable when generating docs 
  hubspot_company_property_history_identifier: "company_property_history_data"
  hubspot_company_identifier: "company_data"
  hubspot_contact_identifier: "contact_data"
  hubspot_contact_merge_audit_identifier: "contact_merge_audit_data"
  hubspot_contact_list_member_identifier: "contact_list_member_data"
  hubspot_contact_property_history_identifier: "contact_property_history_data"
  hubspot_deal_identifier: "deal_data"
  hubspot_deal_stage_identifier: "deal_stage_data"
  hubspot_deal_company_identifier: "deal_company_data"
  hubspot_deal_contact_identifier: "deal_contact_data"
  hubspot_deal_pipeline_identifier: "deal_pipeline_data"
  hubspot_deal_pipeline_stage_identifier: "deal_pipeline_stage_data"
  hubspot_deal_property_history_identifier: "deal_property_history_data"
  hubspot_email_campaign_identifier: "email_campaign_data"
  hubspot_email_event_identifier: "email_event_data"
  hubspot_email_event_bounce_identifier: "email_event_bounce_data"
  hubspot_email_event_click_identifier: "email_event_click_data"
  hubspot_email_event_deferred_identifier: "email_event_deferred_data"
  hubspot_email_event_delivered_identifier: "email_event_delivered_data"
  hubspot_email_event_forward_identifier: "email_event_forward_data"
  hubspot_email_event_open_identifier: "email_event_open_data"
  hubspot_email_event_print_identifier: "email_event_print_data"
  hubspot_email_event_spam_report_identifier: "email_event_spam_report_data"
  hubspot_email_event_status_change_identifier: "email_event_status_change_data"
  hubspot_engagement_identifier: "engagement_data"
  hubspot_engagement_call_identifier: "engagement_call_data"
  hubspot_engagement_company_identifier: "engagement_company_data"
  hubspot_engagement_contact_identifier: "engagement_contact_data"
  hubspot_engagement_deal_identifier: "engagement_deal_data"
  hubspot_engagement_email_identifier: "engagement_email_data"
  hubspot_engagement_meeting_identifier: "engagement_meeting_data"
  hubspot_engagement_note_identifier: "engagement_note_data"
  hubspot_engagement_task_identifier: "engagement_task_data"
  hubspot_owner_identifier: "owner_data"
  hubspot_property_identifier: "property_data"
  hubspot_property_option_identifier: "property_option_data"
  hubspot_ticket_company_identifier: "ticket_company_data"
  hubspot_ticket_contact_identifier: "ticket_contact_data"
  hubspot_ticket_deal_identifier: "ticket_deal_data"
  hubspot_ticket_engagement_identifier: "ticket_engagement_data"
  hubspot_ticket_pipeline_identifier: "ticket_pipeline_data"
  hubspot_ticket_pipeline_stage_identifier: "ticket_pipeline_stage_data"
  hubspot_ticket_property_history_identifier: "ticket_property_history_data"
  hubspot_ticket_identifier: "ticket_data"
  hubspot_contact_list_identifier: "contact_list_data"
  hubspot_email_event_sent_identifier: "email_event_sent_data"
  hubspot_email_event_dropped_identifier: "email_event_dropped_data"
  hubspot_merged_deal_identifier: "merged_deal_data"

  hubspot:
    contact: "{{ ref('stg_hubspot__contact') }}"
    contact_merge_audit: "{{ ref('stg_hubspot__contact_merge_audit') }}"
    contact_list: "{{ ref('stg_hubspot__contact_list') }}"
    contact_list_member: "{{ ref('stg_hubspot__contact_list_member') }}"
    contact_property_history: "{{ ref('stg_hubspot__contact_property_history') }}"
    company: "{{ ref('stg_hubspot__company') }}"
    company_property_history: "{{ ref('stg_hubspot__company_property_history') }}"
    deal: "{{ ref('stg_hubspot__deal') }}"
    merged_deal: "{{ ref('stg_hubspot__merged_deal') }}"
    deal_stage: "{{ ref('stg_hubspot__deal_stage') }}"
    deal_company: "{{ ref('stg_hubspot__deal_company') }}"
    deal_pipeline: "{{ ref('stg_hubspot__deal_pipeline') }}"
    deal_pipeline_stage: "{{ ref('stg_hubspot__deal_pipeline_stage') }}"
    deal_property_history: "{{ ref('stg_hubspot__deal_property_history') }}"
    owner: "{{ ref('stg_hubspot__owner') }}"
    email_event_bounce: "{{ ref('stg_hubspot__email_event_bounce') }}"
    email_event_click: "{{ ref('stg_hubspot__email_event_click') }}"
    email_event_deferred: "{{ ref('stg_hubspot__email_event_deferred') }}"
    email_event_delivered: "{{ ref('stg_hubspot__email_event_delivered') }}"
    email_event_dropped: "{{ ref('stg_hubspot__email_event_dropped') }}"
    email_event_forward: "{{ ref('stg_hubspot__email_event_forward') }}"
    email_event_open: "{{ ref('stg_hubspot__email_event_open') }}"
    email_event_print: "{{ ref('stg_hubspot__email_event_print') }}"
    email_event_sent: "{{ ref('stg_hubspot__email_event_sent') }}"
    email_event_spam_report: "{{ ref('stg_hubspot__email_event_spam_report') }}"
    email_event_status_change: "{{ ref('stg_hubspot__email_event_status_change') }}"
    email_event: "{{ ref('stg_hubspot__email_event') }}"
    engagement: "{{ ref('stg_hubspot__engagement') }}"
    engagement_call: "{{ ref('stg_hubspot__engagement_call') }}"
    engagement_company: "{{ ref('stg_hubspot__engagement_company') }}"
    engagement_contact: "{{ ref('stg_hubspot__engagement_contact') }}"
    engagement_deal: "{{ ref('stg_hubspot__engagement_deal') }}"
    engagement_email_cc: "{{ ref('stg_hubspot__engagement_email_cc') }}"
    engagement_email_to: "{{ ref('stg_hubspot__engagement_email_to') }}"
    engagement_email: "{{ ref('stg_hubspot__engagement_email') }}"
    engagement_meeting: "{{ ref('stg_hubspot__engagement_meeting') }}"
    engagement_note: "{{ ref('stg_hubspot__engagement_note') }}"
    engagement_task: "{{ ref('stg_hubspot__engagement_task') }}"
    
    ticket_company: "{{ ref('stg_hubspot__ticket_company') }}"
    ticket_contact: "{{ ref('stg_hubspot__ticket_contact') }}"
    ticket_deal: "{{ ref('stg_hubspot__ticket_deal') }}"
    ticket_engagement: "{{ ref('stg_hubspot__ticket_engagement') }}"
    ticket_pipeline: "{{ ref('stg_hubspot__ticket_pipeline') }}"
    ticket_pipeline_stage: "{{ ref('stg_hubspot__ticket_pipeline_stage') }}"
    ticket_property_history: "{{ ref('stg_hubspot__ticket_property_history') }}"
    ticket: "{{ ref('stg_hubspot__ticket') }}"
    
    hubspot_contact_merge_audit_enabled: false
models:
  hubspot:
    +materialized: table
    marketing:
      intermediate:
        +materialized: ephemeral
        int_hubspot__contact_merge_adjust:
          +materialized: table
    sales:
      intermediate:
        +materialized: ephemeral
