name: 'google_ads_source'
version: '0.11.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  ad_stats: "{{ source('google_ads','ad_stats') }}"
  ad_history: "{{ source('google_ads','ad_history') }}"
  ad_group_history: "{{ source('google_ads','ad_group_history') }}"
  campaign_history: "{{ source('google_ads','campaign_history') }}"
  account_history: "{{ source('google_ads','account_history') }}"
  ad_group_criterion_history: "{{ source('google_ads','ad_group_criterion_history') }}"
  ad_group_stats: "{{ source('google_ads','ad_group_stats') }}"
  campaign_stats: "{{ source('google_ads','campaign_stats') }}"
  keyword_stats: "{{ source('google_ads','keyword_stats') }}"
  account_stats: "{{ source('google_ads','account_stats') }}"
  google_ads__ad_group_stats_passthrough_metrics: []
  google_ads__ad_stats_passthrough_metrics: []
  google_ads__campaign_stats_passthrough_metrics: []
  google_ads__keyword_stats_passthrough_metrics: []
  google_ads__account_stats_passthrough_metrics: []
models:
  google_ads_source:
    +schema: google_ads_source
    +materialized: table
    tmp:
      +materialized: view
