name: 'synthea_omop_etl'
version: '0.1.0'
config-version: 2

profile: 'synthea_omop_etl'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"

vars:
  seed_source: true

models:
  synthea_omop_etl:
    +materialized: table

seeds:
  synthea_omop_etl:
    map:
      +enabled: true
      +schema: map_seeds
    omop:
      +enabled: true
      +schema: omop_seeds
    vocabulary:
      +enabled: true
      +schema: vocab_seeds
    synthea:
      +enabled: true
      +schema: synthea_seeds
      allergies:
        +column_types:
          CODE: varchar
          REACTION1: varchar
      careplans:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
      claims_transactions:
        +column_types:
          PROCEDURECODE: varchar
          AMOUNT: numeric
          UNITAMOUNT: numeric
          PAYMENTS: numeric
          ADJUSTMENTS: numeric
          TRANSFERS: numeric
          OUTSTANDING: numeric
      claims:
        +column_types:
          DIAGNOSIS1: varchar
          DIAGNOSIS2: varchar
          DIAGNOSIS3: varchar
          DIAGNOSIS4: varchar
          DIAGNOSIS5: varchar
          DIAGNOSIS6: varchar
          DIAGNOSIS7: varchar
          DIAGNOSIS8: varchar
          REFERRINGPROVIDERID: varchar
      conditions:
        +column_types:
          CODE: varchar
      devices:
        +column_types:
          CODE: varchar
          STOP: timestamp
      encounters:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
          BASE_ENCOUNTER_COST: numeric
          TOTAL_CLAIM_COST: numeric
          PAYER_COVERAGE: numeric
      imaging_studies:
        +column_types:
          CODE: varchar
          BODYSITE_CODE: varchar
          MODALITY_CODE: varchar
          SOP_CODE: varchar
          PROCEDURE_CODE: varchar
      immunizations:
        +column_types:
          CODE: varchar
          BASE_COST: numeric
      medications:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
          BASE_COST: numeric
          PAYER_COVERAGE: numeric
          TOTALCOST: numeric
      observations:
        +column_types:
          CODE: varchar
      patients:
        +column_types:
          SUFFIX: varchar
          ZIP: varchar
      procedures:
        +column_types:
          CODE: varchar
          REASONCODE: varchar
          BASE_COST: numeric
      supplies:
        +column_types:
          CODE: varchar
