version: 2

models:
  - name: int_greenhouse__application_users
    description: Table capturing applications and the internal users involved in each one.
    columns:
      - name: applied_at
        description: Timestamp of when the application was submitted. 
      - name: candidate_id
        description: Foreign key referencing the CANDIDATE who submitted the application.
      - name: credited_to_user_id
        description: Foreign key referencing the USER who will receive credit for this application.
      - name: current_stage_id
        description: Foreign key referencing the JOB_STAGE that the application is currently at in the pipeline. 
      - name: application_id
        description: Unique ID of the application.
        tests:
          - unique
          - not_null
      - name: last_activity_at
        description: Timestamp of when the last activity was taken on this application. 
      - name: location_address
        description: The content of the address question on a job post.
      - name: is_prospect
        description: >
          Boolean that is true if this is a prospect application, which means that the associated person 
          is a prospect and has not yet applied for this job.
      - name: prospect_owner_user_id
        description: Foreign key referencing the USER ID of the prospect owner.
      - name: prospect_pool_id
        description: Foreign key referencing the PROSPECT_POOL that the application came from.
      - name: prospect_stage_id
        description: Foreign key referencing the ID of the application's PROSPECT_POOL_STAGE.
      - name: rejected_at
        description: Timestamp of when the application was rejected. 
      - name: rejected_reason_id
        description: Foreign key referencing the REJECTION_REASON for the application.
      - name: source_id
        description: Foreign key referencing the ID of the SOURCE of the application.
      - name: status
        description: One of - active, rejected, hired.
      - name: referrer_name
        description: Full name of the user who is credited with referring this application.
      - name: prospect_owner_name
        description: Full name of the prospect owner.

  - name: int_greenhouse__application_info
    description: Table capturing information about applications 
    columns:
      - name: applied_at
        description: Timestamp of when the application was submitted. 
      - name: candidate_id
        description: Foreign key referencing the CANDIDATE who submitted the application.
      - name: credited_to_user_id
        description: Foreign key referencing the USER who will receive credit for this application.
      - name: current_stage_id
        description: Foreign key referencing the JOB_STAGE that the application is currently at in the pipeline. 
      - name: application_id
        description: Unique ID of the application.
      - name: last_activity_at
        description: Timestamp of when the last activity was taken on this application. 
      - name: location_address
        description: The content of the address question on a job post.
      - name: is_prospect
        description: >
          Boolean that is true if this is a prospect application, which means that the associated person 
          is a prospect and has not yet applied for this job.
      - name: prospect_owner_user_id
        description: Foreign key referencing the USER ID of the prospect owner.
      - name: prospect_pool_id
        description: Foreign key referencing the PROSPECT_POOL that the application came from.
      - name: prospect_stage_id
        description: Foreign key referencing the ID of the application's PROSPECT_POOL_STAGE.
      - name: rejected_at
        description: Timestamp of when the application was rejected. 
      - name: rejected_reason_id
        description: Foreign key referencing the REJECTION_REASON for the application.
      - name: source_id
        description: Foreign key referencing the ID of the SOURCE of the application.
      - name: status
        description: One of - active, rejected, hired.
      - name: referrer_name
        description: Full name of the user who is credited with referring this application.
      - name: prospect_owner_name
        description: Full name of the prospect owner.
      - name: current_company
        description: The company at which the candidate currently works.
      - name: coordinator_user_id
        description: Foreign key referencing the USER who is responsible for coordinating this candidate.
      - name: candidate_created_at
        description: Timestamp of when the candidate profile was created. 
      - name: full_name
        description: First and last name of the candidate.
      - name: is_private
        description: Boolean that is true if the candidate is private. 
      - name: recruiter_user_id
        description: Foreign key referencing the USER who is the recruiter assigned to this candidate.
      - name: current_title
        description: The candidate's current title.
      - name: last_updated_at
        description: Timestamp of when the candidate profile was last updated.
      - name: phone
        description: Comma-separated aggregated list of the candidate's phone numbers and the type of phone they are.
      - name: email
        description: Comma-separated list of the candidate's email addresses. 
      - name: resume_url
        description: URL of the candidate's most recently uploaded resume. 
      - name: linkedin_url
        description: URL of the candidate's most recently added LinkedIn link. 
      - name: github_url
        description: URL of the candidate's most recently added Github link. 
      - name: coordinator_name
        description: Full name of the user who is responsible for coordinating with this candidate.
      - name: recruiter_name
        description: Full name of the candidate's assigned recruiter.
      - name: coordinator_email
        description: Email of the user who is responsible for coordinating with this candidate.
      - name: recruiter_email
        description: Email of the candidate's assigned recruiter.
      - name: candidate_tags
        description: Comma-separated list of tags attached to this candidate. 
      - name: current_job_stage
        description: Current stage that the application is at in the hiring pipeline. 
      - name: sourced_from
        description: Where the application was sourced from. 
      - name: sourced_from_type
        description: The category of source that the application came from. 
      - name: count_activities
        description: Total count of activities completed on this candidate's profile.
      - name: job_title
        description: Title of the job role the candidate is applying for. 
      - name: job_offices
        description: Semicolon-separated list of the offices that the job is listed under. 
      - name: job_departments
        description: Semicolon-separated list of the departments that the job is listed under. 
      - name: job_parent_departments
        description: Semicolon-separated list of the *parent* departments that the job is listed under. 
      - name: job_status
        description: Current status of the job being applied for.
      - name: hiring_managers
        description: Comma-separated list of the full names of the job's hiring managers.
      - name: job_id
        description: Foreign key referencing the JOB being applied for. 
      - name: job_requisition_id
        description: The id of the requisition corresponding to this job posting, if applicable.
      - name: job_sourcers
        description: Comma-separated list of the full names of the job's recruiting sourcers. 
      - name: prospect_pool
        description: Name given to the applicant's prospect pool. 
      - name: prospect_stage
        description: Current stage of the applicant within its prospect pool, if applicable. 
      - name: candidate_gender
        description: Description of the applicant's gender identity.
      - name: candidate_disability_status
        description: Description of the applicant's disability status.
      - name: candidate_race
        description: Description of applicant's provided race.
      - name: candidate_veteran_status
        description: Description of the applicant's veteran status.
      - name: application_job_key
        description: >
          Unique key hashed on `application_id` and `job_id`. This has to be done as the table contains both 
          candidates and prospects.
        tests:
          - unique
          - not_null