name: 'berlin_bike_theft'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'biketheft'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


models:
  berlin_bike_theft:
    staging:
      materialized: view
    core:
      materialized: table

seeds: 
  berlin_bike_theft:
    reported_incidents_daily:
      +column_types:
        TATZEIT_ANFANG_DATUM: string
        TATZEIT_ENDE_DATUM: string
    mapping_berlin_lor:
      +delimiter: ";"
