name: mrr_project
profile: mrr
version: '1.0'
config-version: 2

require-dbt-version: ">=0.19.0"

source-paths: ["models"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

models:
  mrr_project:
    materialized: table


