{% macro get_pa0031_columns() %}

{% set columns = [
    {"name": "_fivetran_deleted", "datatype": "boolean"},
    {"name": "_fivetran_rowid", "datatype": dbt.type_numeric()},
    {"name": "_fivetran_synced", "datatype": dbt.type_timestamp()},
    {"name": "aedtm", "datatype": dbt.type_string()},
    {"name": "begda", "datatype": dbt.type_string()},
    {"name": "endda", "datatype": dbt.type_string()},
    {"name": "flag1", "datatype": dbt.type_string()},
    {"name": "flag2", "datatype": dbt.type_string()},
    {"name": "flag3", "datatype": dbt.type_string()},
    {"name": "flag4", "datatype": dbt.type_string()},
    {"name": "grpvl", "datatype": dbt.type_string()},
    {"name": "histo", "datatype": dbt.type_string()},
    {"name": "itbld", "datatype": dbt.type_string()},
    {"name": "itxex", "datatype": dbt.type_string()},
    {"name": "mandt", "datatype": dbt.type_string()},
    {"name": "objps", "datatype": dbt.type_string()},
    {"name": "ordex", "datatype": dbt.type_string()},
    {"name": "pernr", "datatype": dbt.type_string()},
    {"name": "preas", "datatype": dbt.type_string()},
    {"name": "refex", "datatype": dbt.type_string()},
    {"name": "rese1", "datatype": dbt.type_string()},
    {"name": "rese2", "datatype": dbt.type_string()},
    {"name": "rfp01", "datatype": dbt.type_string()},
    {"name": "rfp02", "datatype": dbt.type_string()},
    {"name": "rfp03", "datatype": dbt.type_string()},
    {"name": "rfp04", "datatype": dbt.type_string()},
    {"name": "rfp05", "datatype": dbt.type_string()},
    {"name": "rfp06", "datatype": dbt.type_string()},
    {"name": "rfp07", "datatype": dbt.type_string()},
    {"name": "rfp08", "datatype": dbt.type_string()},
    {"name": "rfp09", "datatype": dbt.type_string()},
    {"name": "rfp10", "datatype": dbt.type_string()},
    {"name": "rfp11", "datatype": dbt.type_string()},
    {"name": "rfp12", "datatype": dbt.type_string()},
    {"name": "rfp13", "datatype": dbt.type_string()},
    {"name": "rfp14", "datatype": dbt.type_string()},
    {"name": "rfp15", "datatype": dbt.type_string()},
    {"name": "rfp16", "datatype": dbt.type_string()},
    {"name": "rfp17", "datatype": dbt.type_string()},
    {"name": "rfp18", "datatype": dbt.type_string()},
    {"name": "rfp19", "datatype": dbt.type_string()},
    {"name": "rfp20", "datatype": dbt.type_string()},
    {"name": "seqnr", "datatype": dbt.type_string()},
    {"name": "sprps", "datatype": dbt.type_string()},
    {"name": "subty", "datatype": dbt.type_string()},
    {"name": "uname", "datatype": dbt.type_string()}
] %}

{{ return(columns) }}

{% endmacro %}