name: 'zuora'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]


profile: 'zuora'

vars:
  zuora_schema: main
  zuora_source:
    zuora_account_identifier: "zuora_account_data"
    zuora_amendment_identifier: "zuora_amendment_data"
    zuora_contact_identifier: "zuora_contact_data"
    zuora_credit_balance_adjustment_identifier: "zuora_credit_balance_adjustment_data"
    zuora_invoice_identifier: "zuora_invoice_data"
    zuora_invoice_item_identifier: "zuora_invoice_item_data" 
    zuora_invoice_payment_identifier: "zuora_invoice_payment_data" 
    zuora_order_identifier: "zuora_order_data"
    zuora_payment_identifier: "zuora_payment_data"
    zuora_payment_method_identifier: "zuora_payment_method_data"
    zuora_product_identifier: "zuora_product_data"
    zuora_product_rate_plan_identifier: "zuora_product_rate_plan_data"
    zuora_product_rate_plan_charge_identifier: "zuora_product_rate_plan_charge_data"
    zuora_rate_plan_identifier: "zuora_rate_plan_data"
    zuora_rate_plan_charge_identifier: "zuora_rate_plan_charge_data"
    zuora_refund_identifier: "zuora_refund_data"
    zuora_refund_invoice_payment_identifier: "zuora_refund_invoice_payment_data"
    zuora_subscription_identifier: "zuora_subscription_data"
    zuora_taxation_item_identifier: "zuora_taxation_item_data"

  zuora: 
    account: "{{ ref('stg_zuora__account') }}" 
    amendment: "{{ ref('stg_zuora__amendment') }}"
    contact: "{{ ref('stg_zuora__contact') }}"
    credit_balance_adjustment: "{{ ref('stg_zuora__credit_balance_adjustment') }}"
    invoice: "{{ ref('stg_zuora__invoice') }}"
    invoice_item: "{{ ref('stg_zuora__invoice_item') }}"
    invoice_payment: "{{ ref('stg_zuora__invoice_payment') }}" 
    order: "{{ ref('stg_zuora__order') }}" 
    payment: "{{ ref('stg_zuora__payment') }}"
    payment_method: "{{ ref('stg_zuora__payment_method') }}"
    product_rate_plan_charge: "{{ ref('stg_zuora__product_rate_plan_charge') }}"
    product_rate_plan: "{{ ref('stg_zuora__product_rate_plan') }}"
    product: "{{ ref('stg_zuora__product') }}"
    rate_plan_charge: "{{ ref('stg_zuora__rate_plan_charge') }}"
    rate_plan: "{{ ref('stg_zuora__rate_plan') }}"
    refund: "{{ ref('stg_zuora__refund') }}"
    refund_invoice_payment: "{{ ref('stg_zuora__refund_invoice_payment') }}"
    subscription: "{{ ref('stg_zuora__subscription') }}"
    taxation_item: "{{ ref('stg_zuora__taxation_item') }}"

  zuora_account_pass_through_columns: []
  zuora_rate_plan_pass_through_columns: []
  zuora_rate_plan_charge_pass_through_columns: []
  zuora_subscription_pass_through_columns: []

models:
  zuora:
    +materialized: table
    intermediate:
      +materialized: table

  
seeds:
  main:
    +column_types:
      _fivetran_synced: "timestamp"
      amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      amount_home_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      balance: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      bill_cycle_day: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      cancelled_date: "timestamp"
      cancelled_on: "timestamp"
      created_date: "timestamp"
      current_term: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      exchange_rate: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      mrr: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      quantity: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      renewal_term: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
      submitted_on: "timestamp"
      tax_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
      updated_date: "timestamp"
    zuora_account_data:
      +column_types:
        credit_balance: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        last_invoice_date: "timestamp"
        tax_exempt_effective_date: "timestamp"
        tax_exempt_expiration_date: "timestamp"
        total_debit_memo_balance: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        total_invoice_balance: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        unapplied_balance: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        unapplied_credit_memo_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    zuora_invoice_data:
      +column_types:
        adjustment_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        amount_without_tax: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        amount_without_tax_home_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}" 
        credit_balance_adjustment_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        credit_memo_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        last_email_sent_date: "timestamp"
        payment_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        posted_date: "timestamp"
    zuora_invoice_item_data:
      +column_types: 
        charge_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        charge_amount_home_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        charge_date: "timestamp"
        unit_price: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    zuora_invoice_payment_data:
      +column_types:
        amount_currency_rounding: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}" 
    zuora_payment_data:
      +column_types:  
        applied_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        applied_credit_balance_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"  
        settled_on: "timestamp"
        unapplied_amount: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    zuora_payment_method_data:
      +column_types:
        credit_card_country: string
        last_failed_sale_transaction_date: "timestamp"
        last_transaction_date_time: "timestamp"
        max_consecutive_payment_failures: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        num_consecutive_failures: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        total_number_of_error_payments: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        total_number_of_processed_payments: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    zuora_product_rate_plan_charge_data:
      +column_types:
        default_quantity: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        included_units: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        max_quantity: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        min_quantity: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}" 
        specific_billing_period:  "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
        up_to_periods: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}"
    zuora_rate_plan_charge_data:
      +column_types:
        booking_exchange_rate: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        dmrc: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        dmrchome_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        dtcv: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        dtcvhome_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}" 
        mrrhome_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        price_increase_percentage: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        tcv: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
        tcvhome_currency: "{{ 'FLOAT64' if target.type == 'bigquery' else 'float' }}"
    zuora_refund_data:
      +column_types: 
        refund_transaction_time: "timestamp"
        refund_date: "timestamp"
    zuora_subscription_data:
      +column_types: 
        contract_acceptance_date: "timestamp"
        contract_effective_date: "timestamp"
        created_date: "timestamp"
        initial_term: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}" 
        original_created_date: "timestamp"
        service_activation_date: "timestamp"
        subscription_end_date: "timestamp"
        subscription_start_date: "timestamp"
        term_end_date: "timestamp"
        term_start_date: "timestamp"
        version: "{{ 'INT64' if target.type == 'bigquery' else 'bigint' }}" 
    zuora_taxation_item_data:
      +column_types:  
        tax_date: "timestamp"
