name: 'facebook_pages'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  posts: "{{ ref('stg_facebook_pages__post_history') }}"
  pages: "{{ ref('stg_facebook_pages__page') }}"
  post_metrics: "{{ ref('stg_facebook_pages__lifetime_post_metrics_total') }}"
  page_metrics: "{{ ref('stg_facebook_pages__daily_page_metrics_total') }}"
models:
  facebook_pages:
    +schema: facebook_pages
    +materialized: table
