config-version: 2
name: 'asana_source'
version: 0.8.0
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  asana_source:
    +schema: stg_asana
    materialized: table
vars:
  asana_source:
    user: "{{ source('asana', 'user') }}"
    project: "{{ source('asana', 'project') }}"
    task: "{{ source('asana', 'task') }}"
    story: "{{ source('asana', 'story') }}"
    team: "{{ source('asana', 'team') }}"
    tag: "{{ source('asana', 'tag') }}"
    project_task: "{{ source('asana', 'project_task') }}"
    task_follower: "{{ source('asana', 'task_follower') }}"
    task_tag: "{{ source('asana', 'task_tag') }}"
    section: "{{ source('asana', 'section') }}"
    task_section: "{{ source('asana', 'task_section') }}"
    task_pass_through_columns: []
