danish_democracy_data:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: 'danish_democracy_data.duckdb'
      extensions:
        - httpfs
        - parquet
      external_root: 'data/curated'