version: 2


models:
  - name: base_airports
    description: |
      The cleaned version of `raw_airports`.

      _Note: The default materialisation of this table is `ephemeral`,
      but it is overridden in the SQL to be materialised as a `table` instead.
      This is so that indexes can be assigned._

    columns:
      - name: airport_id
        description: "Unique OpenFlights identifier for this airport."
        tests:
          - not_null

      - name: name
        description: "Name of airport. May or may not contain the City name."
      
      - name: city
        description: "Main city served by airport. May be spelled differently from Name."

      - name: country
        description: >
          Country or territory where airport is located.
          See [Countries](https://openflights.org/data.html#country) to cross-reference to ISO 3166-1 codes.

      - name: iata
        description: "3-letter IATA code. `Null` if not assigned/unknown."

      - name: icao
        description: "4-letter ICAO code. `Null` if not assigned."

      - name: latitude
        description: "Decimal degrees, usually to six significant digits. Negative is South, positive is North."

      - name: longitude
        description: "Decimal degrees, usually to six significant digits. Negative is West, positive is East."

      - name: altitude
        description: "In feet."

      - name: timezone
        description: |
          Hours offset from UTC.

          Fractional hours are expressed as decimals, eg. India is 5.5.

      - name: dst
        description: |
          Daylight savings time.

          One of E (Europe), A (US/Canada), S (South America),
          O (Australia), Z (New Zealand), N (None) or U (Unknown).

          See also: [Help: Time](https://openflights.org/help/time.html)

      - name: database_time_zone
        description: >
          Timezone in ["tz" (Olson) format](http://en.wikipedia.org/wiki/Tz_database),
          eg. "America/Los_Angeles".

      - name: type
        description: |
          Type of the airport.

          Value "airport" for air terminals, "station" for train stations,
          "port" for ferry terminals and "unknown" if not known.

          In this table, only type=airport is included.

      - name: source
        description: |
          Source of this data.

          "OurAirports" for data sourced from [OurAirports](http://ourairports.com/data/),
          "Legacy" for old data not matched to OurAirports (mostly DAFIF),
          "User" for unverified user contributions.

          In this table, only source=OurAirports is included.



  - name: base_arrivals__malaysia
    description: |
      The cleaned version of `raw_arrivals`.

      Transformation made were:
      - Named table to reflect that data only has Malaysian airports.
      - Renaming of columns to be more descriptive.
      - Casting strings columns to proper Postgres type.
      - Add additional column(s) for more context.

      _Note: The default materialisation of this table is `ephemeral`,
      but it is overridden in the SQL to be materialised as a `table` instead.
      This is so that indexes can be assigned._

    columns:
      - name: sort_time_utc
        description: "The timestamp (UTC) that FlightStats uses to sort flights in their system."

      - name: arrival_timestamp
        description: "The timestamp (MYT) of the expected flight arrival _(i.e. `sort_time_utc + 8 hours` )_."

      - name: operated_by
        description: "A description of the flight operator and on behalf of other airlines, if any."

      - name: full_url
        description: "The full URL users can open and be directed to the respective flight status page."
        tests:
          - not_null
          - unique

      - name: arrival_date
        description: "The arrival date."

      - name: arrival_iata
        description: "3-letter IATA code for the arrival airport."

      - name: arrival_icao
        description: "4-letter ICAO code for the arrival airport."

      - name: arrival_airport_name
        description: "The name of the arrival (destination) airport."
        tests:
          - not_null

      - name: departure_time_time_am_pm
        description: >
          The published departure time (local to the airport) for the flight
          provided by the airline's operating schedule in AM/PM.

      - name: departure_time_time_24
        description: >
          The published departure time (local to the airport) for the flight
          provided by the airline's operating schedule in 24-hour military time.

      - name: arrival_time_time_am_pm
        description: >
          The published arrival time (local to the airport) for the flight
          provided by the airline's operating schedule in AM/PM.

      - name: arrival_time_time_24
        description: >
          The published arrival time (local to the airport) for the flight
          provided by the airline's operating schedule in 24-hour military time.

      - name: carrier_fs
        description: "The Cirium code for the carrier, globally unique across time."

      - name: carrier_name
        description: "The name of the carrier."

      - name: carrier_flight_number
        description: "The flight identification number and any additional characters."

      - name: departure_airport_fs
        description: "The Cirium code for the departure airport, globally unique across time."

      - name: departure_airport_city
        description: "The city with which the departure airport is associated."

      - name: is_code_share
        description: >
          Boolean value indicating if the marketed flight is a
          [codeshare](http://en.wikipedia.org/wiki/Codeshare_agreement)
        tests:
          - accepted_values:
              values:
                - "true"
                - "false"
