config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]

name: 'sap_source'
version: '0.1.0'

models:
  sap_source:
    +materialized: table
    +schema: stg_sap

vars:
  sap_source:
    bkpf: "{{ source('sap', 'bkpf') }}"
    bseg: "{{ source('sap', 'bseg') }}"
    faglflexa: "{{ source('sap', 'faglflexa') }}"
    faglflext: "{{ source('sap', 'faglflext') }}"
    lfa1: "{{ source('sap', 'lfa1') }}"
    kna1: "{{ source('sap', 'kna1') }}"
    mara: "{{ source('sap', 'mara') }}"
    pa0000: "{{ source('sap', 'pa0000') }}"
    pa0001: "{{ source('sap', 'pa0001') }}"
    pa0007: "{{ source('sap', 'pa0007') }}"
    pa0008: "{{ source('sap', 'pa0008') }}"
    pa0031: "{{ source('sap', 'pa0031') }}" 
    ska1: "{{ source('sap', 'ska1') }}"
    t001: "{{ source('sap', 't001') }}"
    t503: "{{ source('sap', 't503') }}"
    t880: "{{ source('sap', 't880') }}"

clean-targets:
  - target
  - dbt_modules
  - dbt_packages