name: 'inzight'
version: '1.0.0'
config-version: 2

profile: 'inzight'

vars:
  "dbt_date:time_zone": "Europe/Brussels"

dispatch:
  - macro_namespace: dbt_utils
    search_order: [dbt_duckdb_utils, dbt_utils]
  - macro_namespace: dbt_expectations
    search_order: [dbt_duckdb_utils, dbt_expectations]
  - macro_namespace: dbt_date
    search_order: [dbt_duckdb_utils, dbt_date]

models:
  inzight:
    +materialized: table
