version: 2

models:
  - name: prod_posts_ghosts
    description: Cleansed table which contains posts from subreddits of paranormal stuff.
    columns:
      - name: author_post
        tests:
          - not_null
      - name: distinguished_post
        tests:
          - not_null
      - name: edited_post
        tests:
          - not_null
      - name: post_id
        tests:
          - unique
          - not_null
      - name: post_is_original_content
        tests:
          - not_null
      - name: post_locked
        tests:
          - not_null
      - name: post_fullname
        tests:
          - not_null
          - unique
      # post title could be repeated because the same post
      # exists in another subreddit
      - name: post_title
        tests:
          - not_null
      - name: post_text
        tests:
          - not_null
      - name: num_comments
        tests:
          - not_null
      - name: post_score
        tests:
          - not_null
      - name: post_url
        tests:
          - unique
          - not_null
      - name: post_created_at
        tests:
          - not_null
      - name: post_over_18
        tests:
          - not_null
      - name: post_spoiler
        tests:
          - not_null
      - name: post_stickied
        tests:
          - not_null
      - name: post_upvote_ratio
        tests:
          - not_null

  - name: prod_comments_ghosts
    description: Cleansed table of comments from posts in paranormal subreddits
    columns:
      - name: comments_post_url
        tests:
          - not_null
      - name: author_comment
        tests:
          - not_null
      - name: comment_id
        tests:
          - not_null
          - unique
      - name: comment_body
        tests:
          - not_null
      - name: comment_created_at
        tests:
          - not_null
      - name: comment_distinguished
        tests:
          - not_null
      - name: comment_edited
        tests:
          - not_null
      - name: is_author_submitter
        tests:
          - not_null
      - name: comments_post_id
        tests:
          - not_null
      - name: link_comment
        tests:
          - not_null
          - unique
      - name: comment_score
        tests:
          - not_null

