
version: 2

sources:
    - name: raw
      schema: main

      tables:
        - name: posts_ghosts
          identifier : raw_posts_ghosts
        - name: comments_ghosts
          identifier : raw_comments_ghosts  