name: acme

profile: playbook

version: '1.0'

source-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  database: false
  identifier: false
  schema: false

seeds:
  quote_columns: false
  acme:
    sessions:
      csv_options:
        delimiter: ','
        header: True

models:
  transient: true
