name: 'google_ads'
version: '0.11.0'

config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  +materialized: table

profile: 'google_ads'

vars:
  google_ads_schema: main
  google_ads_source:
    google_ads_ad_stats_identifier: "ad_stats_data"
    google_ads_ad_history_identifier: "ad_history_data"
    google_ads_ad_group_history_identifier: "ad_group_history_data"
    google_ads_campaign_history_identifier: "campaign_history_data"
    google_ads_account_history_identifier: "account_history_data"
    google_ads_keyword_stats_identifier: "keyword_stats_data"
    google_ads_account_stats_identifier: "account_stats_data"
    google_ads_ad_group_stats_identifier: "ad_group_stats_data"
    google_ads_campaign_stats_identifier: "campaign_stats_data"
    google_ads_ad_group_criterion_history_identifier: "ad_group_criterion_history_data"

    google_ads__campaign_stats_passthrough_metrics:
      - name: conversions
      - name: view_through_conversions
        alias: view_through_conversions_aliased


  google_ads:
    ad_stats: "{{ ref('stg_google_ads__ad_stats') }}"
    account_history: "{{ ref('stg_google_ads__account_history') }}"
    campaign_history: "{{ ref('stg_google_ads__campaign_history') }}"
    ad_group_history: "{{ ref('stg_google_ads__ad_group_history') }}"
    ad_history: "{{ ref('stg_google_ads__ad_history') }}"
    ad_group_criterion_history: "{{ ref('stg_google_ads__ad_group_criterion_history') }}"
    ad_group_stats: "{{ ref('stg_google_ads__ad_group_stats') }}"
    campaign_stats: "{{ ref('stg_google_ads__campaign_stats') }}"
    keyword_stats: "{{ ref('stg_google_ads__keyword_stats') }}"
    account_stats: "{{ ref('stg_google_ads__account_stats') }}"

