version: 2

sources:
  - name: main
    tables:
      - name: album
      - name: artist
      - name: customer
      - name: employee
      - name: genre
      - name: invoice_line
      - name: invoice
      - name: media_type
      - name: playlist_track
      - name: playlist
      - name: track