version: 2

models:
  - name: stg_events
    description: This is the table of events that users took when using JaffleGaggle 
    columns:
      - name: event_id
        description: Primary key of the table
        tests:
          - unique
          - not_null
      - name: user_id
        description: Foreign key to users
      - name: event_name
        description: This is the event that the user took at this timestamp
        tests:
        - accepted_values:
            values: ['recipe_viewed', 'order_placed', 'recipe_favorited']
      - name: timestamp
  
  - name: stg_users
    description: This is the table of users that are using JaffleGaggle
    columns:
      - name: user_id
        description: Primary key of the table
        tests:
          - unique
          - not_null
      - name: email
        tests:
            - unique
            - not_null
      - name: email_domain
        description: Extracted email domain from the user's email
      - name: gaggle_id
        description: Foreign key to gaggles
        tests:
            - not_null
      - name: created_at

  - name: stg_gaggles
    description: This is the table of gaggles on the platform
    columns:
      - name: gaggle_id
        description: Primary key of the table
        tests:
          - unique
          - not_null
      - name: gaggle_name
      - name: created_at
