{{
	config(
		materialized="incremental",
		alias="monthly_agg_reviews",
		schema="main",
		unique_key="DATE_SENTIMENT_ID"
	)
}}

WITH review_cte AS (
	SELECT *
	FROM {{ref('fct_reviews')}}
)

SELECT
	COUNT(*) AS REVIEW_TOTALS,
	REVIEW_SENTIMENT,
	STRFTIME('%m-%Y', REVIEW_DATE) AS MONTH_YEAR, -- 使用 STRFTIME 替代 TO_CHAR
	EXTRACT(MONTH FROM REVIEW_DATE) AS MONTH,
	EXTRACT(YEAR FROM REVIEW_DATE) AS YEAR,
	{{dbt_utils.surrogate_key(['CAST(EXTRACT(MONTH FROM REVIEW_DATE) AS TEXT)',
							   'CAST(EXTRACT(YEAR FROM REVIEW_DATE) AS TEXT)',
							   'REVIEW_SENTIMENT'])}} AS DATE_SENTIMENT_ID
FROM review_cte

{% if is_incremental() %}
WHERE 
	EXTRACT(MONTH FROM REVIEW_DATE) = EXTRACT(MONTH FROM CURRENT_DATE)
	AND EXTRACT(YEAR FROM REVIEW_DATE) = EXTRACT(YEAR FROM CURRENT_DATE)
{% endif %}

GROUP BY
	REVIEW_SENTIMENT,
	MONTH_YEAR,
	MONTH,
	YEAR,
	DATE_SENTIMENT_ID
ORDER BY
	YEAR DESC,
	MONTH DESC
