config-version: 2
name: 'pendo_source'
version: '0.5.0'
require-dbt-version: [">=1.3.0", "<2.0.0"]
models:
  pendo_source:
    tmp:
      +materialized: view
    +materialized: table
    +schema: stg_pendo
vars:
  pendo_source:
    account_history: "{{ source('pendo', 'account_history') }}"
    application_history: "{{ source('pendo', 'application_history') }}"
    event: "{{ source('pendo', 'event') }}"
    feature_event: "{{ source('pendo', 'feature_event') }}"
    feature_history: "{{ source('pendo', 'feature_history') }}"
    group: "{{ source('pendo', 'group') }}"
    guide_event: "{{ source('pendo', 'guide_event') }}"
    guide_history: "{{ source('pendo', 'guide_history') }}"
    guide_step_history: "{{ source('pendo', 'guide_step_history') }}"
    page_event: "{{ source('pendo', 'page_event') }}"
    page_history: "{{ source('pendo', 'page_history') }}"
    page_rule_history: "{{ source('pendo', 'page_rule_history') }}"
    user: "{{ source('pendo', 'user') }}"
    visitor_history: "{{ source('pendo', 'visitor_history') }}"
    poll: "{{ source('pendo', 'poll') }}"
    poll_event: "{{ source('pendo', 'poll_event') }}"
    visitor_account_history: "{{ source('pendo', 'visitor_account_history') }}"
    pendo__event_pass_through_columns: []
    pendo__feature_event_pass_through_columns: []
    pendo__page_event_pass_through_columns: []
    pendo__account_history_pass_through_columns: []
    pendo__visitor_history_pass_through_columns: []
