config-version: 2

name: 'apple_store_source_integration_tests'
version: '0.4.0'

profile: 'integration_tests' 

vars:
  # apple_store__using_subscriptions: True # un-comment this line when generating docs!
  apple_store_schema: apple_store_source_integrations_tests
  apple_store_source:
    apple_store_app_identifier: "app"
    apple_store_app_store_platform_version_source_type_report_identifier: "app_store_platform_version_source_type"
    apple_store_app_store_source_type_device_report_identifier: "app_store_source_type_device"
    apple_store_app_store_territory_source_type_report_identifier: "app_store_territory_source_type"
    apple_store_crashes_app_version_device_report_identifier: "crashes_app_version"
    apple_store_crashes_platform_version_device_report_identifier: "crashes_platform_version"
    apple_store_downloads_platform_version_source_type_report_identifier: "downloads_platform_version_source_type"
    apple_store_downloads_source_type_device_report_identifier: "downloads_source_type_device"
    apple_store_downloads_territory_source_type_report_identifier: "downloads_territory_source_type"
    apple_store_sales_account_identifier: "sales_account"
    apple_store_sales_subscription_event_summary_identifier: "sales_subscription_events"
    apple_store_sales_subscription_summary_identifier: "sales_subscription_summary"
    apple_store_usage_app_version_source_type_report_identifier: "usage_app_version_source_type"
    apple_store_usage_platform_version_source_type_report_identifier: "usage_platform_version_source_type"
    apple_store_usage_source_type_device_report_identifier: "usage_source_type_device"
    apple_store_usage_territory_source_type_report_identifier: "usage_territory_source_type"

models:
  +persist_docs:
    relation: "{{ false if target.type in ('spark','databricks') else true }}"
    columns: "{{ false if target.type in ('spark','databricks') else true }}"

seeds:
  apple_store_source_integration_tests:
    +quote_columns: "{{ true if target.type == 'redshift' else false }}"
    +column_types:
      _fivetran_synced: timestamp
      date: timestamp
      
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']