name: 'marketo_source_integration_tests'
version: '0.11.0'
profile: 'integration_tests'
config-version: 2
vars:
  marketo_schema: marketo_source_integration_tests_7
  marketo_source:
    marketo_lead_identifier: "marketo_lead_data"
    marketo_lead_describe_identifier: "marketo_lead_describe_data"
    marketo_activity_change_data_value_identifier: "marketo_activity_change_data_value_data"
    marketo_campaign_identifier: "marketo_campaign_data"
    marketo_program_identifier: "marketo_program_data"
    marketo_email_template_history_identifier: "marketo_email_template_history_data"
    marketo_activity_click_email_identifier: "marketo_activity_click_email_data"
    marketo_activity_email_delivered_identifier: "marketo_activity_email_delivered_data"
    marketo_activity_email_bounced_identifier: "marketo_activity_email_bounced_data"
    marketo_activity_open_email_identifier: "marketo_activity_open_email_data"
    marketo_activity_unsubscribe_email_identifier: "marketo_activity_unsubscribe_email_data"
    marketo_activity_send_email_identifier: "marketo_activity_send_email_data"
    marketo_activity_delete_lead_identifier: "marketo_activity_delete_lead_data"
    marketo_activity_merge_leads_identifier: "marketo_activity_merge_leads_data"

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']