name: 'twitter_organic'
version: '0.3.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<2.0.0"]
vars:
  account_history_staging: "{{ ref('stg_twitter_organic__account_history') }}"
  organic_tweet_report_staging: "{{ ref('stg_twitter_organic__organic_tweet_report') }}"
  tweet_staging: "{{ ref('stg_twitter_organic__tweet') }}"
  users_staging: "{{ ref('stg_twitter_organic__twitter_user_history') }}"
models:
  twitter_organic:
    +schema: twitter_organic
    +materialized: table
